config/routes.rb
Myapp::Application.routes.draw do
  
  


  
  get "contact_messages/new"

  get 'business_signup', to: 'business_accounts#new', as: 'business_signup'
  get 'business_login', to: 'business_sessions#new', as: 'business_login'
  get 'business_logout', to: 'business_sessions#destroy', as: 'business_logout'
  
  get 'business_accounts/change_password', to: 'business_accounts#change_password'
  post 'business_accounts/send_change_password', to: 'business_accounts#send_change_password'
  resources :business_accounts
  
  get 'business_sessions/reset_password', to: 'business_sessions#reset_password'
  post 'business_sessions/send_new_password', to: 'business_sessions#send_new_password'
  resources :business_sessions

  get 'business/dashboard', to: 'businesses#dashboard', as: 'business/dashboard'
  get 'business/adverts', to: 'businesses#adverts', as: 'business/adverts'
  match 'business/web_vouchers', to: 'businesses#web_vouchers', via: [:get, :post]
  get 'business/wv_payment_cancelled', to: 'businesses#wv_payment_cancelled'
  get 'business/wv_payment_accepted', to: 'businesses#wv_payment_accepted'
  get 'business/ad_payment_cancelled', to: 'businesses#ad_payment_cancelled'
  get 'business/ad_payment_accepted', to: 'businesses#ad_payment_accepted'
  get 'business/new_book_advert', to: 'businesses#new_book_advert'
  post 'business/create_book_advert', to: 'businesses#create_book_advert'
  get 'business/directory', to: 'businesses#directory'
  post 'business/process_review', to: 'businesses#process_review'
  get 'business/search', to: 'businesses#search'
  get 'business/my_events', to: 'businesses#my_events'
  resources :businesses

  # Manager Area
  get 'manager', to: 'manager#index', as: 'manager/index'
  get "manager/dashboard", to: 'manager#dashboard', as: 'manager/dashboard'
  get 'manager/booklets', to: 'manager#booklets', as: 'manager/booklets'
  get 'manager/businesses', to: 'manager#businesses', as: 'manager/businesses'
  get 'manager/web_vouchers', to: 'manager#web_vouchers', as: 'manager/web_vouchers'
  get 'manager/settings', to: 'manager#settings', as: 'manager/settings'
  get 'manager/towns', to: 'manager#towns', as: 'manager/towns'
  get 'manager/business_categories', to: 'manager#business_categories', as: 'manager/business_categories'
  get 'manager/advert_sizes', to: 'manager#advert_sizes', as: 'manager/advert_sizes'
  get 'manager/add_credits', to: 'manager#add_credits', as: 'manager/add_credits'
  post 'manager/update_credits', to: 'manager#update_credits', as: 'manager/update_credits'
  get 'manager/new_business_account', to: 'manager#new_business_account', as: 'manager/new_business_account'
  post 'manager/create_business_account', to: 'manager#create_business_account', as: 'manager/create_business_account'
  get 'manager/new_business_profile', to: 'manager#new_business_profile', as: 'manager/new_business_profile'
  post 'manager/create_business_profile', to: 'manager#create_business_profile', as: 'manager/create_business_profile'
  get 'manager/edit_business_profile', to: 'manager#edit_business_profile', as: 'manager/edit_business_profile'
  post 'manager/update_business_profile', to: 'manager#update_business_profile', as: 'manager/update_business_profile'
  get 'manager/edit_web_voucher', to: 'manager#edit_web_voucher', as: 'manager/edit_web_voucher'
  put 'manager/update_web_voucher', to: 'manager#update_web_voucher', as: 'manager/update_web_voucher'
  get 'manager/expire_web_voucher', to: 'manager#expire_web_voucher', as: 'manager/expire_web_voucher'
  get 'manager/marketing_email', to: 'manager#marketing_email', as: 'manager/marketing_email'
  post 'manager/send_marketing_email', to: 'manager#send_marketing_email', as: 'manager/send_marketing_email'
  get 'manager/new_web_voucher', to: 'manager#new_web_voucher'
  post 'manager/create_web_voucher', to: 'manager#create_web_voucher'
  get 'manager/set_advert_paid', to: 'manager#set_advert_paid'
  get 'manager/articles', to: 'manager#articles'
  get 'manager/business_reviews', to: 'manager#business_reviews'
  get 'manager/edit_review', to: 'manager#edit_review'
  put 'manager/update_review', to: 'manager#update_review', as: 'manager/update_review'
  get 'manager/sign_in_as_business', to: 'manager#sign_in_as_business'
  
  get 'contacts/create_a_business_listing', to: 'contacts#create_a_business_listing'
  get 'contacts/totally_delete_contact', to: 'contacts#totally_delete_contact'
  post 'contacts/add_contact_note', to: 'contacts#add_contact_note'
  resources :contacts
  resources :commissions
  resources :events
  resources :appointments
  resources :testimonials
  
  # Manager Reports
  get 'manager/reports', to: 'manager#reports'
  get 'manager/commission_report', to: 'manager#commission_report'
  get 'manager/commission_by_booklet', to: 'manager#commission_by_booklet'
  get 'manager/commission_by_booklet_print', to: 'manager#commission_by_booklet_print'
  
  get 'manager/create_contacts_from_existing_businesses', to: 'manager#create_contacts_from_existing_businesses'
  
  resources :towns
  resources :business_categories
  resources :advert_sizes
  
  resources :booklets
  
  resources :paypal_payments

  get 'print_voucher', to: 'web_vouchers#print', as: 'print_voucher'
  get 'web_vouchers/by_category'
  get 'web_vouchers/by_town'
  get 'web_vouchers/expire_voucher'
  resources :web_vouchers
  
  

  get 'advert/invoice', to: 'adverts#invoice'
  get 'print_invoice', to: 'adverts#print', as: 'print_invoice'
  get 'advert/pay_advert', to: 'adverts#pay_advert'
  resources :adverts
  
  get 'advert_comments/accept_design', to: 'advert_comments#accept_design'
  resources :advert_comments
  
  match 'articles/category', to: 'articles#category'
  resources :articles
  resources :article_comments

  # Static Pages
  get 'advertising', to: 'pages#advertising'
  get 'contact_us', to: 'pages#contact'
  post 'send_contact_form', to: 'pages#send_contact_form'
  get 'advert_enquiry', to: 'pages#advert_enquiry'
  post 'send_advert_enquiry', to: 'pages#send_advert_enquiry'

  get 'restaurant_vouchers', to: 'pages#restaurant_vouchers'
  get 'health_and_beauty_vouchers', to: 'pages#health_and_beauty_vouchers'
  get 'bars_pubs_and_clubs_vouchers', to: 'pages#bars_vouchers'
  get 'fast_food_and_takeaway_vouchers', to: 'pages#takeaway_vouchers'
  get 'motoring_vouchers', to: 'pages#motoring_vouchers'
  get 'fashion_vouchers', to: 'pages#fashion_vouchers'

  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms', to: 'pages#terms'
  
  get 'newsletter/unsubscribe', to: 'newsletters#unsubscribe'
  resources :newsletters
  
  # Error pages (404 etc)
  match "404", to: "errors#not_found"
  

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'web_vouchers#index'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  protect_from_forgery :except => :web_vouchers
	before_filter :authorise_business, except: [:index, :show, :directory, :process_review, :search]
	

  def index
    @page_title = BUS_INDEX_PAGE_TITLE
    @meta_desc = BUS_INDEX_META_DESC
    @meta_key = BUS_INDEX_META_KEY

    @businesses = Business.all
  end

  def directory
    @businesses = Business.order('business_name ASC').paginate(:page => params[:page], :per_page => BUSINESSES_PER_PAGE)

    @page_title = BUS_INDEX_PAGE_TITLE
    @meta_desc = BUS_INDEX_META_DESC
    @meta_key = BUS_INDEX_META_KEY
  end

  def search
    @businesses = Business.search(params[:what], params[:where]).paginate(:page => params[:page], :per_page => BUSINESSES_PER_PAGE)
  end

  def show
    @business = Business.find_by_business_name(params[:id])
    if @business.nil?
      redirect_to business_directory_path, alert: "Sorry, that business does not exist"
    else
    
      @page_title = "#{@business.business_name} in #{@business.town}"
      @meta_desc = BUS_INDEX_META_DESC
      @meta_key = BUS_INDEX_META_KEY

        
      @vouchers = WebVoucher.where('business_account_id = ? AND status = ?', @business.business_account_id, 'Paid').not_expired.order('created_at DESC')
      @reviews = BusinessReview.where('business_id = ? AND published = ? AND active = ?', @business.id, true, true).order('created_at DESC')
      @rating = @reviews.collect(&:rating).sum.to_f/@reviews.length if @reviews.length > 0  
    
    end
  end

  def new
  	@business = Business.find_by_business_account_id(current_business.id)
  	if(@business.blank?)
  		@business = Business.new
  	else
  		render "edit"
  	end
  	
  end

  def process_review
    @review = BusinessReview.new(business_id: params[:business_id], email: params[:email], name: params[:name], rating: params[:rating], comments: params[:comments], published: false, active: false)
    if @review.save
      redirect_to business_path(@review.business.business_name), notice: "Thanks. Your review has been submitted and will appear shortly."
    else
      redirect_to business_path(@review.business.business_name), alert: "There was a problem adding your review, please try again"
    end
  end

  def create
  	@business = Business.new(params[:business])
  	@business.business_account_id = current_business.id
  	if @business.save
  	  # Add voucher credits to their account
  	  WebVoucherCredit.create(business_account_id: current_business.id, credits: FREE_CREDIT_AMOUNT)
  	  ContactMailer.new_business_profile(@business).deliver
  		redirect_to business_dashboard_path, notice: "Thanks, your business profile has been created. You have been credited with #{FREE_CREDIT_AMOUNT} free credits to create web vouchers; enjoy!"
  	else
  		flash.now[:error] = "There were problems creating your profile"
  		render "new"
  	end
  end

  def edit
  	@business = Business.find_by_business_account_id(current_business.id)
  	if(@business.blank?)
  		redirect_to new_business_path
  	else
  		render "edit"
  	end
  end

  def update
  	@business = Business.find_by_business_account_id(current_business.id)
  	if @business.update_attributes(params[:business])
  		redirect_to business_dashboard_path, notice: "Thanks, your business profile has been updated."
  	else
  		render "edit"
  	end
  end

  def dashboard
  	@business = Business.find_by_business_account_id(current_business.id)
    if(@business.blank?)
      redirect_to new_business_path, notice: "Please set up your business profile."
    else
      @latest_adverts = Advert.where('business_id = ?', current_business.business.id).order('created_at DESC').limit(3)
  	  @latest_web_vouchers = WebVoucher.where('business_account_id = ? AND status = ?', current_business, 'Paid').order('created_at DESC').limit(3)
  	  @credits = WebVoucherCredit.find_by_business_account_id(current_business)
	  end
  end
  
  def adverts
    @adverts = Advert.where('business_id = ?', current_business.business).paginate(:page => params[:page], :per_page => BUSINESS_ADMIN_VOUCHERS_PER_PAGE)
  end

  def web_vouchers
    @adverts = WebVoucher.where('business_account_id = ? AND status = ?', current_business, 'Paid').order('created_at DESC').paginate(:page => params[:page], :per_page => BUSINESS_ADMIN_VOUCHERS_PER_PAGE)
    @credits = WebVoucherCredit.find_by_business_account_id(current_business)
      
  end

  def wv_payment_accepted
    redirect_to business_web_vouchers_path, notice: "Thanks for your purchase, your web voucher has been created"
  end

  def wv_payment_cancelled
    redirect_to business_web_vouchers_path, alert: "Your purchase was cancelled :( If there was a problem, please let us know."
  end

  def ad_payment_accepted
    redirect_to business_adverts_path, notice: "Thanks for your payment."
  end

  def ad_payment_cancelled
    redirect_to business_adverts_path, alert: "Your payment has been cancelled. Your advert requires payment before it is printed in the booklet. Please contact us if you have any issues."
  end

  def new_book_advert
    @advert = Advert.new
  end

  def create_book_advert
    @advert = Advert.new(:booklet_id => params[:booklet_id], :advert_size_id => params[:advert_size_id])
    @advert.business_id = current_business.business.id

    if @advert.save
      # send email to admin regarding new request
      ContactMailer.new_booklet_advert_request(current_business.business, @advert.booklet_id, @advert).deliver
      redirect_to business_dashboard_path, notice: "Your booklet voucher request has been accepted. You will be contacted shortly regarding your requirements."
    else
      redirect_to business_dashboard_path, alert: "There was a problem creating your voucher advertisement. Please contact us."
    end
  end

  def my_events
    @events = Event.where('business_id = ?', current_business.business.id).order('date_to DESC').paginate(:page => params[:page], :per_page => 10)
  end
  
end

app/helpers/businesses_helper.rb
module BusinessesHelper

	def rating_display(score)
  	if score == 0
  		disp =  "<i class='icon-star-empty'></i> <i class='icon-star-empty'></i> <i class='icon-star-empty'></i> <i class='icon-star-empty'></i> <i class='icon-star-empty'></i>"
  	elsif score == 1
  		disp =  "<i class='icon-star'></i> <i class='icon-star-empty'></i> <i class='icon-star-empty'></i> <i class='icon-star-empty'></i> <i class='icon-star-empty'></i>"
  	elsif score == 2
  		disp =  "<i class='icon-star'></i> <i class='icon-star'></i> <i class='icon-star-empty'></i> <i class='icon-star-empty'></i> <i class='icon-star-empty'></i>"
  	elsif score == 3
  		disp =  "<i class='icon-star'></i> <i class='icon-star'></i> <i class='icon-star'></i> <i class='icon-star-empty'></i> <i class='icon-star-empty'></i>"
  	elsif score == 4
  		disp =  "<i class='icon-star'></i> <i class='icon-star'></i> <i class='icon-star'></i> <i class='icon-star'></i> <i class='icon-star-empty'></i>"
  	else score == 5
  		disp =  "<i class='icon-star'></i> <i class='icon-star'></i> <i class='icon-star'></i> <i class='icon-star'></i> <i class='icon-star'></i>"
  	end
  end

end

app/views/businesses/_businesses.html.erb
<div class="two-thirds">
                <% for business in @businesses %>
                    <div class="introbox">
                        
                                <div class="one-third">
                                    <% if !business.image.to_s.blank? %>
                                        <p><%= image_tag business.image.to_s, width: "150", class: "not-top" %></p>
                                    <% end %>
                                    <%= link_to "View Details", business_path(business), class: "button large blue" %><br />
                                    <% reviews = business.business_reviews.select { |review| review.published == true } %>
                                    <% score = reviews.length > 0 ? rating_display(reviews.collect(&:rating).sum.to_f/reviews.length) : rating_display(0) %>
                                    <strong>Rating:</strong> <%= score.html_safe %><br />
                                    <%= pluralize(reviews.count, "review") %>
                                </div>

                                <div class="two-thirds column-last textalignleft">
                                    <h1><strong><%= link_to business.business_name, business_path(business) %></strong></h1>
                                    <p>
                                        <i class="<%= business.business_category.icon %>"></i> <%= business.business_category.name %><br />
                                        <%= business.business_name %><br />
                                        <%= business.street %><br />
                                        <%= business.town %><br />
                                        <%= business.county %><br />
                                        <%= business.postcode %><br />
                                        <%= business.telephone %>
                                    </p>
                                    <% if !business.about_us.blank? %>
                                        <p><%= truncate(business.about_us, :omission => "#{link_to ' ...more', business_path(business)}", :length => 100).html_safe %></p>
                                    <% end %>
                                </div>
                                
                                <div class="clear"></div>
                        
                    </div>
                <% end %>

                <%= will_paginate @businesses %>

            </div> <!-- end two-thirds -->

app/views/businesses/_menu.html.erb
    <!-- begin content -->
    <section id="content" class="container clearfix">
<!-- begin sidebar -->
  <aside id="sidebar" class="one-fourth">
      <div class="widget">
        <p><strong>Welcome <%= current_business.business.business_name %></strong></p>

          <h3>Menu</h3>	
          <nav>
              <ul class="menu">
                <li><%= link_to "Dashboard", business_dashboard_path %></li>
                <li><%= link_to "Web Vouchers", business_web_vouchers_path %></li>
									<li><%= link_to "Booklet Adverts", business_adverts_path %></li>
                  <li><%= link_to "Events", business_my_events_path %></li>
                  <li>&nbsp;</li>
                  <li><%= link_to "Profile", edit_business_path(current_business) %></li>
									<li><%= link_to "Change Password", business_accounts_change_password_path %></li>
                  <li>&nbsp;</li>
                  <li><%= link_to "Log Out", business_logout_path %></li>
              </ul>
          </nav>
      </div>
  </aside>
  <!-- end sidebar -->

app/views/businesses/adverts.html.erb
<!-- begin page title -->
    <section id="page-title">
        <div class="container clearfix">
            <h1>Business Dashboard - Booklet Adverts</h1>
        </div>
    </section>
    <!-- end page title -->

<%= render 'businesses/menu' %>
  
<!-- begin main content -->
  <section id="main" class="three-fourths column-last">
      <h2>Booklet Adverts</h2>
      <p>Booklet adverts are advertisements / vouchers that are printed in our monthly voucher books.</p>

      <p><%= link_to "New Booklet Voucher", business_new_book_advert_path, class: 'button blue' %></p>

			<table class="gen-table">
				<thead>
					<tr>
						<th>Booklet Name</th>
						<th>Advert Size</th>
						<th>Advert Cost</th>
						<th>Paid?</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					<% if @adverts.any? %>
						<% @adverts.each do |ad| %>
							<tr>
								<% has_paid = ad.paid == true ? '<i class="icon-ok green"></i>' : '<i class="icon-remove red"></i>' %>
								<% needs_to_pay = ad.paid == true ? "" : "| Pay" %>
								<td><%= ad.booklet.name %></td>
								<td><%= ad.advert_size.name %></td>
								<td><%= number_to_currency(ad.advert_cost) %></td>
								<td><%= has_paid.html_safe %></td>
								<td><%= link_to "View", advert_path(ad) %> <%= needs_to_pay %> </td>
							</tr>
						<% end %>
					<% else %>
						<tr>
							<td colspan="5">You have no adverts placed in our monthly booklet. If you would be interested in advertising, please <%= link_to "contact us", advert_enquiry_path %>.</td>
						</tr>
					<% end %>
				</tbody>
			</table>
  </section>
  <!-- end main content -->
</section>
<!-- end content -->

app/views/businesses/dashboard.html.erb
<!-- begin page title -->
    <section id="page-title">
        <div class="container clearfix">
            <h1>Business Dashboard</h1>
        </div>
    </section>
    <!-- end page title -->
    	<%= render 'businesses/menu' %>
        
		<!-- begin main content -->
        <section id="main" class="three-fourths column-last">
					<h2>Latest Web Vouchers</h2>
					<% if @credits && @credits.credits > 0 %>
						<p>You currently have <strong><%= pluralize(@credits.credits, 'credit') %></strong> remaining.</p>
					<% end %>
				<table class="gen-table">
					<thead>
						<tr>
							<th>Title</th>
							<th>Expires</th>
							<th>Analytics<br />Views | Prints</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<% if @latest_web_vouchers.any? %>
							<% @latest_web_vouchers.each do |ad| %>
							<tr>
								<td><%= ad.title %></td>
								<% expired = ad.expiry_date < Date.today ? "Expired" : "#{pluralize((ad.expiry_date - Date.today).to_i, "Days")} left" %>
								<td><strong><%= l ad.expiry_date %></strong> (<%= expired %>)</td>
								<td><%= get_web_voucher_views(ad.id) %> | <%= get_web_voucher_prints(ad.id) %></td>
								<!-- <td>-- Coming Soon --</td> -->
								<% if has_expired?(ad.id) %>
									<td>Expired</td>
								<% else %>
									<td><%= link_to "Edit", edit_web_voucher_path(ad.id) %> | <%= link_to "Expire", web_vouchers_expire_voucher_path(id: ad.id), confirm: 'Are you sure? This voucher will no longer be shown on the website!' %></td>
								<% end %>
							</tr>
							<% end %>
						<% else %>
							<tr>
								<td colspan='4'>You have not created any web vouchers yet. Would you like to <%= link_to "create one now?", new_web_voucher_path %>
							</tr>	
						<% end %>
					</tbody>
				</table>
				<%= link_to "New Web Voucher", new_web_voucher_path, class: 'button blue' %> <%= link_to "View All Web Vouchers", business_web_vouchers_path, class: "button" %>
	
	
           <h2 class="mtop30">Latest Booklet Adverts</h2>
		      <table class="gen-table">
						<thead>
							<tr>
								<th>Booklet Name</th>
								<th>Advert Size</th>
								<th>Advert Cost</th>
								<th>Paid?</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							<% if @latest_adverts.any? %>
								<% @latest_adverts.each do |lad| %>
									<tr>
										<% has_paid = lad.paid == true ? '<i class="icon-ok green"></i>' : '<i class="icon-remove red"></i>' %>
										<% needs_to_pay = lad.paid == true ? "" : "| #{link_to 'Pay', advert_pay_advert_path(id: lad)}" %>
										<td><%= lad.booklet.name %></td>
										<td><%= lad.advert_size.name %></td>
										<td><%= number_to_currency(lad.advert_cost) %></td>
										<td><%= has_paid.html_safe %></td>
										<td><%= link_to "View", advert_path(lad) %> <%= needs_to_pay.html_safe %> </td>
									</tr>
								<% end %>
							<% else %>
								<tr>
									<td colspan="5">You have no adverts placed in our monthly booklet. If you would be interested in advertising, please <%= link_to 'Contact Us', advert_enquiry_path %>.</td>
								</tr>
							<% end %>
						</tbody>
					</table>
					<%= link_to "New Booklet Voucher", business_new_book_advert_path, class: 'button blue' %> <%= link_to "View All Booklet Adverts", business_adverts_path, class: "button" %>

					
            
        </section>
        <!-- end main content -->
    </section>
    <!-- end content --> 

app/views/businesses/directory.html.erb
<!-- begin page title -->
    <section id="page-title">
    	<div class="container clearfix">
				<h1>Business Directory</h1>
        </div>
    </section>
    <!-- end page title -->
    
    <!-- begin content -->
    <section id="content" class="container clearfix">

        <%= render 'businesses/search_form' %>
    	
        <section>
	
        	<%= render 'businesses/businesses' %>

            <div class="cat-menu">    
                <div class="one-third column-last">

                  <%= render 'layouts/side_business_login' %>

                  <%= render 'layouts/side_blog' %>
                    
                    <div class="clear"></div>
                </div>
            </div>

        </section>
        
    </section>
    <!-- end content -->  

app/views/businesses/edit.html.erb
<!-- begin page title -->
    <section id="page-title">
        <div class="container clearfix">
            <h1>Edit Your Business Profile</h1>
        </div>
    </section>
    <!-- end page title -->  

    <%= render 'businesses/menu' %>
        
        <!-- begin main content -->
        <section id="main" class="three-fourths column-last">
            <h2>Edit Your Business Details</h2>
                <%= render 'form' %>
            
        </section>
        <!-- end main content -->
    </section>
    <!-- end content --> 

app/views/businesses/my_events.html.erb
<!-- begin page title -->
    <section id="page-title">
        <div class="container clearfix">
            <h1>Business Dashboard - My Events</h1>
        </div>
    </section>
    <!-- end page title -->
    	<%= render 'businesses/menu' %>
        
		<!-- begin main content -->
        <section id="main" class="three-fourths column-last">
        	<h2>My Events</h2>
            <p><%= link_to "Create Event", new_event_path, class: "button" %></p>
			<table class="gen-table">
				<thead>
					<tr>
						<th>Title</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Active?</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					<% @events.each do |event| %>
					<tr>
						<% is_active = event.active == true ? '<i class="icon-ok green"></i>' : '<i class="icon-remove red"></i>' %>
						<td><%= event.title %></td>
						<td><%= l event.date_from %></td>
						<td><%= l event.date_to %></td>
						<td><%= is_active.html_safe %></td>
						<td><%= link_to "Edit", edit_event_path(event) %> | <%= link_to 'Delete', event, method: :delete, confirm: 'Are You Sure?' %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<%= will_paginate @events %>
            
        </section>
        <!-- end main content -->
    </section>
    <!-- end content --> 

app/views/businesses/new.html.erb
<!-- begin page title -->
    <section id="page-title">
        <div class="container clearfix">
            <h1>Create Your Business Profile</h1>
        </div>
    </section>
    <!-- end page title -->

    <section id="content" class="container clearfix">
        <section id="main">
                <h2>Enter Your Business Details</h2>
                <%= render 'form' %>
        </section>
        
        
        
    </section>
    <!-- end content -->  

app/views/businesses/search.html.erb
<!-- begin page title -->
    <section id="page-title">
    	<div class="container clearfix">
				<h1>Search The Business Directory</h1>
        </div>
    </section>
    <!-- end page title -->
    
    <!-- begin content -->
    <section id="content" class="container clearfix">

        <%= render 'businesses/search_form' %>
    	
        <section>
	
        	<%= render 'businesses/businesses' %>

            <div class="cat-menu">    
                <div class="one-third column-last">

                  <%= render 'layouts/side_business_login' %>

                  <%= render 'layouts/side_blog' %>
                    
                    <div class="clear"></div>
                </div>
            </div>

        </section>
        
    </section>
    <!-- end content -->  

app/views/businesses/web_vouchers.html.erb
<!-- begin page title -->
    <section id="page-title">
        <div class="container clearfix">
            <h1>Business Dashboard - Web Vouchers</h1>
        </div>
    </section>
    <!-- end page title -->
    	<%= render 'businesses/menu' %>
        
		<!-- begin main content -->
        <section id="main" class="three-fourths column-last">
        	<h2>Web Vouchers</h2>
            <p><%= link_to "Create Voucher", new_web_voucher_path, class: "button" %></p>
						<% if @credits && @credits.credits > 0 %>
							<p>You currently have <strong><%= pluralize(@credits.credits, 'credit') %></strong> remaining.</p>
						<% end %>
			<table class="gen-table">
				<thead>
					<tr>
						<th>Title</th>
						<th>Expires</th>
						<th>Analytics<br />Views | Prints</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					<% @adverts.each do |ad| %>
					<tr>
						<td><%= ad.title %></td>
						<% expired = ad.expiry_date < Date.today ? "Expired" : "#{pluralize((ad.expiry_date - Date.today).to_i, "Days")} left" %>
						<td><strong><%= l ad.expiry_date %></strong> (<%= expired %>)</td>
						<td><%= get_web_voucher_views(ad.id) %> | <%= get_web_voucher_prints(ad.id) %></td>
						<% if has_expired?(ad.id) %>
							<td>Expired</td>
						<% else %>
							<td><%= link_to "Edit", edit_web_voucher_path(ad.id) %> | <%= link_to "Expire", web_vouchers_expire_voucher_path(id: ad.id), confirm: 'Are you sure? This voucher will no longer be shown on the website!' %></td>
						<% end %>
					</tr>
					<% end %>
				</tbody>
			</table>

			<%= will_paginate @adverts %>
            
        </section>
        <!-- end main content -->
    </section>
    <!-- end content --> 