config/routes.rb
Myapp::Application.routes.draw do
  
  


  
  get "contact_messages/new"

  get 'business_signup', to: 'business_accounts#new', as: 'business_signup'
  get 'business_login', to: 'business_sessions#new', as: 'business_login'
  get 'business_logout', to: 'business_sessions#destroy', as: 'business_logout'
  
  get 'business_accounts/change_password', to: 'business_accounts#change_password'
  post 'business_accounts/send_change_password', to: 'business_accounts#send_change_password'
  resources :business_accounts
  
  get 'business_sessions/reset_password', to: 'business_sessions#reset_password'
  post 'business_sessions/send_new_password', to: 'business_sessions#send_new_password'
  resources :business_sessions

  get 'business/dashboard', to: 'businesses#dashboard', as: 'business/dashboard'
  get 'business/adverts', to: 'businesses#adverts', as: 'business/adverts'
  match 'business/web_vouchers', to: 'businesses#web_vouchers', via: [:get, :post]
  get 'business/wv_payment_cancelled', to: 'businesses#wv_payment_cancelled'
  get 'business/wv_payment_accepted', to: 'businesses#wv_payment_accepted'
  get 'business/ad_payment_cancelled', to: 'businesses#ad_payment_cancelled'
  get 'business/ad_payment_accepted', to: 'businesses#ad_payment_accepted'
  get 'business/new_book_advert', to: 'businesses#new_book_advert'
  post 'business/create_book_advert', to: 'businesses#create_book_advert'
  get 'business/directory', to: 'businesses#directory'
  post 'business/process_review', to: 'businesses#process_review'
  get 'business/search', to: 'businesses#search'
  get 'business/my_events', to: 'businesses#my_events'
  resources :businesses

  # Manager Area
  get 'manager', to: 'manager#index', as: 'manager/index'
  get "manager/dashboard", to: 'manager#dashboard', as: 'manager/dashboard'
  get 'manager/booklets', to: 'manager#booklets', as: 'manager/booklets'
  get 'manager/businesses', to: 'manager#businesses', as: 'manager/businesses'
  get 'manager/web_vouchers', to: 'manager#web_vouchers', as: 'manager/web_vouchers'
  get 'manager/settings', to: 'manager#settings', as: 'manager/settings'
  get 'manager/towns', to: 'manager#towns', as: 'manager/towns'
  get 'manager/business_categories', to: 'manager#business_categories', as: 'manager/business_categories'
  get 'manager/advert_sizes', to: 'manager#advert_sizes', as: 'manager/advert_sizes'
  get 'manager/add_credits', to: 'manager#add_credits', as: 'manager/add_credits'
  post 'manager/update_credits', to: 'manager#update_credits', as: 'manager/update_credits'
  get 'manager/new_business_account', to: 'manager#new_business_account', as: 'manager/new_business_account'
  post 'manager/create_business_account', to: 'manager#create_business_account', as: 'manager/create_business_account'
  get 'manager/new_business_profile', to: 'manager#new_business_profile', as: 'manager/new_business_profile'
  post 'manager/create_business_profile', to: 'manager#create_business_profile', as: 'manager/create_business_profile'
  get 'manager/edit_business_profile', to: 'manager#edit_business_profile', as: 'manager/edit_business_profile'
  post 'manager/update_business_profile', to: 'manager#update_business_profile', as: 'manager/update_business_profile'
  get 'manager/edit_web_voucher', to: 'manager#edit_web_voucher', as: 'manager/edit_web_voucher'
  put 'manager/update_web_voucher', to: 'manager#update_web_voucher', as: 'manager/update_web_voucher'
  get 'manager/expire_web_voucher', to: 'manager#expire_web_voucher', as: 'manager/expire_web_voucher'
  get 'manager/marketing_email', to: 'manager#marketing_email', as: 'manager/marketing_email'
  post 'manager/send_marketing_email', to: 'manager#send_marketing_email', as: 'manager/send_marketing_email'
  get 'manager/new_web_voucher', to: 'manager#new_web_voucher'
  post 'manager/create_web_voucher', to: 'manager#create_web_voucher'
  get 'manager/set_advert_paid', to: 'manager#set_advert_paid'
  get 'manager/articles', to: 'manager#articles'
  get 'manager/business_reviews', to: 'manager#business_reviews'
  get 'manager/edit_review', to: 'manager#edit_review'
  put 'manager/update_review', to: 'manager#update_review', as: 'manager/update_review'
  get 'manager/sign_in_as_business', to: 'manager#sign_in_as_business'
  
  get 'contacts/create_a_business_listing', to: 'contacts#create_a_business_listing'
  get 'contacts/totally_delete_contact', to: 'contacts#totally_delete_contact'
  post 'contacts/add_contact_note', to: 'contacts#add_contact_note'
  resources :contacts
  resources :commissions
  resources :events
  resources :appointments
  resources :testimonials
  
  # Manager Reports
  get 'manager/reports', to: 'manager#reports'
  get 'manager/commission_report', to: 'manager#commission_report'
  get 'manager/commission_by_booklet', to: 'manager#commission_by_booklet'
  get 'manager/commission_by_booklet_print', to: 'manager#commission_by_booklet_print'
  
  get 'manager/create_contacts_from_existing_businesses', to: 'manager#create_contacts_from_existing_businesses'
  
  resources :towns
  resources :business_categories
  resources :advert_sizes
  
  resources :booklets
  
  resources :paypal_payments

  get 'print_voucher', to: 'web_vouchers#print', as: 'print_voucher'
  get 'web_vouchers/by_category'
  get 'web_vouchers/by_town'
  get 'web_vouchers/expire_voucher'
  resources :web_vouchers
  
  

  get 'advert/invoice', to: 'adverts#invoice'
  get 'print_invoice', to: 'adverts#print', as: 'print_invoice'
  get 'advert/pay_advert', to: 'adverts#pay_advert'
  resources :adverts
  
  get 'advert_comments/accept_design', to: 'advert_comments#accept_design'
  resources :advert_comments
  
  match 'articles/category', to: 'articles#category'
  resources :articles
  resources :article_comments

  # Static Pages
  get 'advertising', to: 'pages#advertising'
  get 'contact_us', to: 'pages#contact'
  post 'send_contact_form', to: 'pages#send_contact_form'
  get 'advert_enquiry', to: 'pages#advert_enquiry'
  post 'send_advert_enquiry', to: 'pages#send_advert_enquiry'

  get 'restaurant_vouchers', to: 'pages#restaurant_vouchers'
  get 'health_and_beauty_vouchers', to: 'pages#health_and_beauty_vouchers'
  get 'bars_pubs_and_clubs_vouchers', to: 'pages#bars_vouchers'
  get 'fast_food_and_takeaway_vouchers', to: 'pages#takeaway_vouchers'
  get 'motoring_vouchers', to: 'pages#motoring_vouchers'
  get 'fashion_vouchers', to: 'pages#fashion_vouchers'

  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms', to: 'pages#terms'
  
  get 'newsletter/unsubscribe', to: 'newsletters#unsubscribe'
  resources :newsletters
  
  # Error pages (404 etc)
  match "404", to: "errors#not_found"
  

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'web_vouchers#index'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  
	before_filter :authenticate_admin_user!
  helper_method :commission_rate

  def index
  	# not really needed - will redirect to active admin login page
  	redirect_to manager_dashboard_path
  end

  def dashboard
    if current_admin_user.auth_level == "full"
      @businesses = BusinessAccount.count
      @profiles = Business.count
      @web_vouchers = WebVoucher.not_expired.has_paid.count
      @reviews = BusinessReview.all
    else
      redirect_to appointments_path
    end
  end
  
  def booklets
    @current_booklets = Booklet.where('start_date > ?', Date.today).order('created_at DESC')
    @past_booklets = Booklet.where('start_date < ?', Date.today).order('created_at DESC')
  end

  def set_advert_paid
    @advert = Advert.find(params[:advert])
    @advert.update_attributes(paid: true)
    redirect_to booklet_path(params[:booklet]), notice: "The advert payment status has been changed"
  end
  
  def businesses
    @businesses = Business.order('business_name ASC').paginate(:page => params[:page], :per_page => 20)
  end

  def business_reviews
    @reviews = BusinessReview.order('created_at DESC')
  end

  def edit_review
    @review = BusinessReview.find(params[:id])
  end

  def update_review
    @review = BusinessReview.find(params[:business_review][:id])
    
    if @review.update_attributes(params[:business_review])
      redirect_to manager_business_reviews_path, notice: "The review has been updated"
    else
      redirect_to manager_business_reviews_path, alert: "There was an error updating the review"
    end
  end
  
  def web_vouchers
    @vouchers = WebVoucher.order('expiry_date DESC').paginate(:page => params[:page], :per_page => 20)
  end
  
  def settings
    
  end
  
  def towns
    @towns = Town.all
  end
  
  def business_categories
    @business_categories = BusinessCategory.all
  end
  
  def advert_sizes
    @advert_sizes = AdvertSize.all
  end
  
  def add_credits
    @credits = WebVoucherCredit.find_by_business_account_id(params[:id])
  end

  def update_credits
    @credits = WebVoucherCredit.find_by_business_account_id(params[:bus_id])
    if @credits
      new_total = @credits.credits + params[:credits].to_i
      @credits.update_attributes(credits: new_total)
      redirect_to manager_add_credits_path(id: @credits.business_account_id), notice: 'Credits have been added'
    else
      redirect_to manager_add_credits_path(id: @credits.business_account_id), alert: 'There was a problem adding credits'
    end
  end
  
  def new_business_account
    @business_account = BusinessAccount.new
  end
  
  def create_business_account
    random_password = (0...8).map{ ('a'..'z').to_a[rand(26)] }.join
    @business_account = BusinessAccount.new(email: params[:email], password: random_password, password_confirmation: random_password)
    if @business_account.save
      ContactMailer.new_business_account_password(params[:email], random_password).deliver
      if params[:contact_id]
        redirect_to manager_new_business_profile_path(id: @business_account.id, contact_id: params[:contact_id]), notice: "Please check the contact details are correct"
      else
        redirect_to manager_new_business_profile_path(id: @business_account.id), notice:"The business account has been created. Please add the business details." and return
      end
    else
      redirect_to manager_dashboard_path, alert:"There was a problem creating the business account"
    end
  end
  
  def new_business_profile
    if params[:contact_id]
      @contact = Contact.find(params[:contact_id])
    else
      @contact = nil
    end
  end
  
  def create_business_profile
    @profile = Business.new(business_account_id: params[:business_account_id], business_name: params[:business_name],
                            business_category_id: params[:business_category_id], street: params[:street], town: params[:town], 
                            county: params[:county], postcode: params[:postcode], telephone: params[:telephone], 
                            website: params[:website])
    if @profile.save
      # add business_id to contact
      if params[:contact_id]
        contact = Contact.find(params[:contact_id])
        contact.update_attributes(business_id: @profile.id)
      end
      # add zero credits
      credits = WebVoucherCredit.create(business_account_id: @profile.business_account_id, credits: 0)
      redirect_to manager_dashboard_path, notice:"The business profile has been created"
    else
      redirect_to manager_dashboard_path, alert:"There was a problem creating the business profile"
    end
  end

  def edit_business_profile
    @business = Business.find(params[:id])
  end

  def update_business_profile
    @business = Business.find(params[:business_account_id])
    img = params[:image].blank? ? @business.image : params[:image]
    
    @business.update_attributes(business_name: params[:business_name], business_category_id: params[:business_category_id], street: params[:street], town: params[:town],
                                county: params[:county], postcode: params[:postcode], telephone: params[:telephone], website: params[:website],
                                image: img, about_us: params[:about_us])

    redirect_to manager_businesses_path, notice: "The business profile has been updated"
  end

  def new_web_voucher
    @web_voucher = WebVoucher.new
  end

  def create_web_voucher
    @bus = Business.find_by_business_account_id(params[:business_account_id])
    @web_voucher = WebVoucher.new(:business_account_id => params[:business_account_id], :title => params[:title], :details => params[:details],
                                  :terms => params[:terms], :start_date => Date.today,
                                  :business_category_id => params[:business_category_id], :status => "Paid", :town => @bus.town)
    if @web_voucher.save
      redirect_to manager_web_vouchers_path, notice: "The web voucher has been created"
    else
      redirect_to manager_web_vouchers_path, alert: "There was a problem creating the web voucher"
    end
  end
  
  def edit_web_voucher
    @web_voucher = WebVoucher.find(params[:id])
  end
  
  def update_web_voucher
    @web_voucher = WebVoucher.find(params[:web_voucher][:id])
    
    if @web_voucher.update_attributes(params[:web_voucher])
      redirect_to manager_web_vouchers_path, notice: "The web voucher has been updated"
    else
      redirect_to manager_web_vouchers_path, alert: "There was an error updating the web voucher"
    end
  end
  
  def expire_web_voucher
    @web_voucher = WebVoucher.find(params[:id])
    if @web_voucher
      @web_voucher.update_attributes(:expiry_date => (Date.today - 1.day) )
      redirect_to manager_web_vouchers_path, notice: "The Web Voucher has been expired"
    else
      redirect_to manager_web_vouchers_path, alert: "There was an error expiring your voucher"
    end
    
  end

  def marketing_email
    
  end

  def send_marketing_email
    @emails = params[:email].split(',')
    @emails.each do |email|
      # Check if email exists
      @existing = MarketingEmail.find_by_email(email)
      if !@existing
        @new_email = MarketingEmail.new(:email => email, :subscribed => true)
        @new_email.save
        ContactMailer.marketing_email(email).deliver
      end
    end

    redirect_to manager_marketing_email_path, notice: 'Emails have been sent'
  end
  
  def articles
    @articles = Article.all
  end
  
  
  # Reports Below Here
  
  def reports
    
  end
  
  def commission_report
    @booklets = Booklet.where('start_date < ?', Date.today)
  end
  
  def commission_by_booklet
    @ads = Advert.where('booklet_id = ?', params[:booklet_id])
    @ads_user = @ads.group_by { |t| t.admin_user.fullname}
    @commissions = Commission.all
  end

  def commission_by_booklet_print
    @ads = Advert.where('booklet_id = ?', params[:booklet_id])
    @ads_user = @ads.group_by { |t| t.admin_user.fullname}
    @commissions = Commission.all
    render :layout => false
  end


  def commission_rate(admin, advert)
    Commission.where('admin_user_id = ? AND advert_size_id = ?', admin, advert)
  end
  
  def create_contacts_from_existing_businesses
    businesses = Business.all
    businesses.each do |bus|
      contact = Contact.new(business_name: bus.business_name, telephone: bus.telephone, street: bus.street, town: bus.town, county: bus.county, postcode: bus.postcode, website: bus.website, business_id: bus.id, do_not_contact: false, business_category_id: bus.business_category_id, email: bus.business_account.email)
      contact.save
    end
  end

  def sign_in_as_business
    business_account = BusinessAccount.find_by_id(params[:id])
    session[:business_id] = business_account.id
    redirect_to business_dashboard_path, notice: "Logged in!"
  end
  
end

app/helpers/manager_helper.rb
module ManagerHelper

	
end

app/views/manager/_menu.html.erb
<!-- begin page title -->
    <section id="page-title">
        <div class="container clearfix">
            <h1>Admin Area</h1>
        </div>
    </section>
    <!-- end page title -->

<section id="content" class="container clearfix">
	<div class="manager-icons">
		<h3 class='mbottom20'>Hey, <%= current_admin_user.fullname %>. <%= link_to "Logout", destroy_admin_user_session_path %></h3>
		

		<% if current_admin_user.auth_level == 'basic' %>
			
			<div class="manager-icon-link">
				<%= link_to appointments_path do %>
					<i class="icon-calendar icon-3x"></i> <br />Appointments
				<% end %>
			</div>
			
			<div class="manager-icon-link">
				<%= link_to contacts_path do %>
					<i class="icon-avatar icon-3x"></i> <br />Contacts
				<% end %>
			</div>

			<div class="manager-icon-link">
				<%= link_to manager_businesses_path do %>
					<i class="icon-contact-businesscard icon-3x"></i> <br />Businesses
				<% end %>
			</div>

		<% elsif current_admin_user.auth_level == 'full' %>
		
			<div class="manager-icon-link">
				<%= link_to manager_dashboard_path do %>
					<i class="icon-cog icon-3x"></i> <br />Dashboard
				<% end %>
			</div>
		
			<div class="manager-icon-link">
				<%= link_to appointments_path do %>
					<i class="icon-calendar icon-3x"></i> <br />Appointments
				<% end %>
			</div>
			<div class="manager-icon-link">
				<%= link_to contacts_path do %>
					<i class="icon-avatar icon-3x"></i> <br />Contacts
				<% end %>
			</div>
			<div class="manager-icon-link">
				<%= link_to manager_booklets_path do %>
					<i class="icon-bookalt icon-3x"></i> <br />Booklets
				<% end %>
			</div>
			<div class="manager-icon-link">
				<%= link_to manager_web_vouchers_path do %>
					<i class="icon-coupon icon-3x"></i> <br />Web Vouchers
				<% end %>
			</div>
			<div class="manager-icon-link">
				<%= link_to manager_businesses_path do %>
					<i class="icon-contact-businesscard icon-3x"></i> <br />Businesses
				<% end %>
			</div>
			<div class="manager-icon-link">
				<%= link_to manager_business_reviews_path do %>
					<i class="icon-star icon-3x"></i> <br />Business Reviews
				<% end %>
			</div>
			<div class="manager-icon-link">
				<%= link_to manager_settings_path do %>
					<i class="icon-settingsandroid icon-3x"></i> <br />Settings
				<% end %>
			</div>

		<% end %>

		
	</div>
	<div class="clear"></div>

app/views/manager/commission_by_booklet.html.erb
<%= render 'manager/menu' %>

<section>
	<h2 class="mtop20">Commission By Booklet Report <%= link_to "Print", manager_commission_by_booklet_print_path(booklet_id: @ads.first.booklet.id), class: 'button red small', target: '_blank' %></h2>
	<p><%= link_to "<< Back to reports", manager_commission_report_path, class: 'button green' %></p>
	<h3><%= @ads.first.booklet.name %> Overview</h3>
	
	<table class="gen-table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Adverts</th>
				<th>Pages</th>
				<th>Income</th>
				<th>% age</th>
			</tr>
		</thead>
		<tbody>
			<% total_income = @ads.map { |a| a['advert_cost'] }.reduce(0,:+) %>
			<% @ads_user.sort.each do |user, ads| %>
			<tr>
				<% total_cost = ads.map { |a| a['advert_cost'] }.reduce(0, :+) %>
				<td><strong><%= user %></strong></td>
				<td><%= ads.count %></td>
				<td><%= ((ads.to_a.sum { |item| item.advert_size.page_unit}) / 4.0) %></td>
				<td><%= number_to_currency(total_cost) %></td>
				<td><%= (total_cost / total_income)*100 %>%</td>
			</tr>
			<% end %>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td><strong>Totals</strong></td>
				<td><strong><%= @ads.count %></strong></td>
				<td><strong><%= ((@ads.to_a.sum { |item| item.advert_size.page_unit}) / 4.0) %></strong></td>
				<td><strong><%= number_to_currency( total_income )%></strong></td>
				<td></td>
			</tr>
		</tbody>
	</table>

	<h3 class="mtop30">Breakdown</h3>
	<% @ads_user.sort.each do |user, ads| %>
	<h4 class="mtop20"><%= user %></h4>
	<table class="gen-table">
		<thead>
			<tr>
				<th>Business</th>
				<th>Advert Size</th>
				<th>Ad Income</th>
				<th>Commission</th>
				<th>Fee</th>
			</tr>
		</thead>
		<tbody>	
			<% total_comm = 0 %>		
			<% ads.each do |ad| %>
				<tr>
					<td><%= ad.business.business_name %></td>
					<% comm = commission_rate(ad.admin_user_id, ad.advert_size_id).first.rate %> 
					<% total_comm = total_comm + ( ad.advert_cost * (comm/100) ) %>
					<td><%= ad.advert_size.name %></td>
					<td><%= number_to_currency(ad.advert_cost) %></td>
					<td><%= comm %>%</td>
					<td><%= number_to_currency( ad.advert_cost * (comm/100) )%></td>
				</tr>
			<% end %>
			
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td><strong>Total Commission</strong></td>
				<td><strong><%= number_to_currency(total_comm) %></strong></td>
			</tr>
			
		</tbody>
	</table>
	<% end %>
</section>


</section>

app/views/manager/dashboard.html.erb
<%= render 'manager/menu' %>

<section>
	<h3 class="mtop20">Stats</h3>
	<div class="introbox">
		<table class="gen-table">
		<thead>
			<tr>
				<th>Business Accounts</th>
				<th>Business Profiles</th>
				<th>Web Vouchers</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @businesses %></td>
				<td><%= @profiles %></td>
				<td><%= @web_vouchers %></td>
			</tr>
		</tbody>
	</table>
	</div>
</section>

<section>
	<h3 class="mtop20">Business Reviews</h3>
	<div class="introbox">
		<table class="gen-table">
		<thead>
			<tr>
				<th>Active</th>
				<th>Require Checking</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<% active_review = @reviews.select { |review| review.published == true } %>
				<% to_check = @reviews.select { |review| review.active == false } %>
				<td><%= active_review.size %></td>
				<td><%= to_check.size %></td>
			</tr>
		</tbody>
	</table>
	</div>
</section>


</section>

app/views/manager/edit_business_profile.html.erb
<%= render 'manager/menu' %>

<section>
	<h3 class="mtop20">Add Business Profile</h3>
	
	<%= form_tag manager_update_business_profile_path, :method => :post, class: "content-form" do %>
	
		<p>
      <%= label_tag "business_name", "Business Name" %>
      <%= text_field_tag "business_name", @business.business_name, required: 'required' %>
    </p>
    <p>
      <%= label_tag "business_category_id", "Business Category" %>
      <%= select_tag "business_category_id", options_from_collection_for_select(BusinessCategory.all, "id", "name", @business.business_category_id.to_i) %>
    </p>
    <p>
      <%= label_tag "street", "Street" %>
      <%= text_field_tag "street",@business.street, required: 'required' %>
    </p>
    <p>
      <%= label_tag "town", "Town" %>
      <%= text_field_tag "town", @business.town, required: 'required' %>
    </p>
    <p>
      <%= label_tag "county", "County" %>
      <%= text_field_tag "county", @business.county, required: 'required' %>
    </p>
    <p>
      <%= label_tag "postcode", "Poscode" %>
      <%= text_field_tag "postcode", @business.postcode, required: 'required' %>
    </p>
    <p>
      <%= label_tag "telephone", "Telephone" %>
      <%= text_field_tag "telephone", @business.telephone %>
    </p>
    <p>
      <%= label_tag "website", "Website" %>
      <%= text_field_tag "website", @business.website %>
			<%= hidden_field_tag "business_account_id", @business.id %>
    </p>
    <% unless @business.image.blank? %>
      <p>
        <%= label_tag "Current Logo" %>
        <%= image_tag @business.image_url.to_s %>
      </p>
    <% end %>
    <p>
      <%= label_tag "image", "Logo Upload" %>
      <%= file_field_tag "image" %>
    </p>

    <p>
      <%= label_tag "about_us", "About Us" %>
      <%= text_area_tag "about_us", @business.about_us %>
    </p>
    
    <p><%= submit_tag "Save", class: 'button' %></p>
	
	<% end %>
	
</section>


</section>

app/views/manager/index.html.erb
<h1>Manager#index</h1>
<p>Find me in app/views/manager/index.html.erb</p>

app/views/manager/marketing_email.html.erb
<%= render 'manager/menu' %>

<section>
	<h3 class="mtop20">Send Marketing Email</h3>
	
	<%= form_tag manager_send_marketing_email_path, :method => :post, class: "content-form" do %>
		
		<p>Add list of email addresses separated by commas (,).</p>
		<p><%= text_area_tag 'email', nil, placeholder: 'Email' %></p>
		
		<p><%= submit_tag "Send", class: 'button' %></p>
	
	<% end %>
	
</section>


</section>

app/views/manager/new_web_voucher.html.erb
<%= render 'manager/menu' %>

<section>
	<h3 class="mtop20">New Web Voucher</h3>
	
	<%= form_tag manager_create_web_voucher_path, :method => :post, class: "content-form" do %>
	
		<p>
			<%= label_tag "business_account_id" %>
			<%= select_tag "business_account_id", options_from_collection_for_select(BusinessAccount.all, "id", :name_of_business) %>
		</p>

		<p>
			<%= label_tag "business_category_id" %>
			<%= select_tag "business_category_id", options_from_collection_for_select(BusinessCategory.order('name ASC'), "id", "name") %>
		</p>

		<p>
      		<%= label_tag "title", "Title" %>
      		<%= text_field_tag "title",nil, required: 'required' %>
    	</p>

    	<p>
      		<%= label_tag "details", "Details" %>
      		<%= text_area_tag "details",nil, required: 'required' %>
    	</p>

    	<p>
	      <%= label_tag "terms", "Terms & Conditions" %>
	      <%= text_area_tag "terms",nil, required: 'required' %>
	    </p>

	    <p>
      		<%= label_tag "town", "Town" %>
      		<%= text_field_tag "town",nil, required: 'required' %>
    	</p>



		<p><%= submit_tag "Add", class: 'button' %></p>
	
	<% end %>
	
</section>


</section>

app/views/manager/settings.html.erb
<%= render 'manager/menu' %>

<section>
	<h3 class="mtop20">Settings</h3>
	<div class="one-third">
		<%= render 'manager/settings_menu' %>
	</div>
	
	<div class="two-thirds">
		
	</div>
</section>


</section>

app/views/manager/towns.html.erb
<%= render 'manager/menu' %>

<section>
	<h3 class="mtop20">Settings</h3>
	<div class="one-third">
		<%= render 'manager/settings_menu' %>
	</div>
	
	<div class="two-thirds column-last">
		<h4>Towns</h4>
		<table class="gen-table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<% @towns.each do |town| %>
				<tr>
					<td><%= town.name %></td>
					<td><%= link_to 'Edit', edit_town_path(town) %> | <%= link_to 'Delete', town, method: :delete, confirm: 'Are You Sure?' %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</section>


</section>