config/routes.rb
Myapp::Application.routes.draw do
  
  


  
  get "contact_messages/new"

  get 'business_signup', to: 'business_accounts#new', as: 'business_signup'
  get 'business_login', to: 'business_sessions#new', as: 'business_login'
  get 'business_logout', to: 'business_sessions#destroy', as: 'business_logout'
  
  get 'business_accounts/change_password', to: 'business_accounts#change_password'
  post 'business_accounts/send_change_password', to: 'business_accounts#send_change_password'
  resources :business_accounts
  
  get 'business_sessions/reset_password', to: 'business_sessions#reset_password'
  post 'business_sessions/send_new_password', to: 'business_sessions#send_new_password'
  resources :business_sessions

  get 'business/dashboard', to: 'businesses#dashboard', as: 'business/dashboard'
  get 'business/adverts', to: 'businesses#adverts', as: 'business/adverts'
  match 'business/web_vouchers', to: 'businesses#web_vouchers', via: [:get, :post]
  get 'business/wv_payment_cancelled', to: 'businesses#wv_payment_cancelled'
  get 'business/wv_payment_accepted', to: 'businesses#wv_payment_accepted'
  get 'business/ad_payment_cancelled', to: 'businesses#ad_payment_cancelled'
  get 'business/ad_payment_accepted', to: 'businesses#ad_payment_accepted'
  get 'business/new_book_advert', to: 'businesses#new_book_advert'
  post 'business/create_book_advert', to: 'businesses#create_book_advert'
  get 'business/directory', to: 'businesses#directory'
  post 'business/process_review', to: 'businesses#process_review'
  get 'business/search', to: 'businesses#search'
  get 'business/my_events', to: 'businesses#my_events'
  resources :businesses

  # Manager Area
  get 'manager', to: 'manager#index', as: 'manager/index'
  get "manager/dashboard", to: 'manager#dashboard', as: 'manager/dashboard'
  get 'manager/booklets', to: 'manager#booklets', as: 'manager/booklets'
  get 'manager/businesses', to: 'manager#businesses', as: 'manager/businesses'
  get 'manager/web_vouchers', to: 'manager#web_vouchers', as: 'manager/web_vouchers'
  get 'manager/settings', to: 'manager#settings', as: 'manager/settings'
  get 'manager/towns', to: 'manager#towns', as: 'manager/towns'
  get 'manager/business_categories', to: 'manager#business_categories', as: 'manager/business_categories'
  get 'manager/advert_sizes', to: 'manager#advert_sizes', as: 'manager/advert_sizes'
  get 'manager/add_credits', to: 'manager#add_credits', as: 'manager/add_credits'
  post 'manager/update_credits', to: 'manager#update_credits', as: 'manager/update_credits'
  get 'manager/new_business_account', to: 'manager#new_business_account', as: 'manager/new_business_account'
  post 'manager/create_business_account', to: 'manager#create_business_account', as: 'manager/create_business_account'
  get 'manager/new_business_profile', to: 'manager#new_business_profile', as: 'manager/new_business_profile'
  post 'manager/create_business_profile', to: 'manager#create_business_profile', as: 'manager/create_business_profile'
  get 'manager/edit_business_profile', to: 'manager#edit_business_profile', as: 'manager/edit_business_profile'
  post 'manager/update_business_profile', to: 'manager#update_business_profile', as: 'manager/update_business_profile'
  get 'manager/edit_web_voucher', to: 'manager#edit_web_voucher', as: 'manager/edit_web_voucher'
  put 'manager/update_web_voucher', to: 'manager#update_web_voucher', as: 'manager/update_web_voucher'
  get 'manager/expire_web_voucher', to: 'manager#expire_web_voucher', as: 'manager/expire_web_voucher'
  get 'manager/marketing_email', to: 'manager#marketing_email', as: 'manager/marketing_email'
  post 'manager/send_marketing_email', to: 'manager#send_marketing_email', as: 'manager/send_marketing_email'
  get 'manager/new_web_voucher', to: 'manager#new_web_voucher'
  post 'manager/create_web_voucher', to: 'manager#create_web_voucher'
  get 'manager/set_advert_paid', to: 'manager#set_advert_paid'
  get 'manager/articles', to: 'manager#articles'
  get 'manager/business_reviews', to: 'manager#business_reviews'
  get 'manager/edit_review', to: 'manager#edit_review'
  put 'manager/update_review', to: 'manager#update_review', as: 'manager/update_review'
  get 'manager/sign_in_as_business', to: 'manager#sign_in_as_business'
  
  get 'contacts/create_a_business_listing', to: 'contacts#create_a_business_listing'
  get 'contacts/totally_delete_contact', to: 'contacts#totally_delete_contact'
  post 'contacts/add_contact_note', to: 'contacts#add_contact_note'
  resources :contacts
  resources :commissions
  resources :events
  resources :appointments
  resources :testimonials
  
  # Manager Reports
  get 'manager/reports', to: 'manager#reports'
  get 'manager/commission_report', to: 'manager#commission_report'
  get 'manager/commission_by_booklet', to: 'manager#commission_by_booklet'
  get 'manager/commission_by_booklet_print', to: 'manager#commission_by_booklet_print'
  
  get 'manager/create_contacts_from_existing_businesses', to: 'manager#create_contacts_from_existing_businesses'
  
  resources :towns
  resources :business_categories
  resources :advert_sizes
  
  resources :booklets
  
  resources :paypal_payments

  get 'print_voucher', to: 'web_vouchers#print', as: 'print_voucher'
  get 'web_vouchers/by_category'
  get 'web_vouchers/by_town'
  get 'web_vouchers/expire_voucher'
  resources :web_vouchers
  
  

  get 'advert/invoice', to: 'adverts#invoice'
  get 'print_invoice', to: 'adverts#print', as: 'print_invoice'
  get 'advert/pay_advert', to: 'adverts#pay_advert'
  resources :adverts
  
  get 'advert_comments/accept_design', to: 'advert_comments#accept_design'
  resources :advert_comments
  
  match 'articles/category', to: 'articles#category'
  resources :articles
  resources :article_comments

  # Static Pages
  get 'advertising', to: 'pages#advertising'
  get 'contact_us', to: 'pages#contact'
  post 'send_contact_form', to: 'pages#send_contact_form'
  get 'advert_enquiry', to: 'pages#advert_enquiry'
  post 'send_advert_enquiry', to: 'pages#send_advert_enquiry'

  get 'restaurant_vouchers', to: 'pages#restaurant_vouchers'
  get 'health_and_beauty_vouchers', to: 'pages#health_and_beauty_vouchers'
  get 'bars_pubs_and_clubs_vouchers', to: 'pages#bars_vouchers'
  get 'fast_food_and_takeaway_vouchers', to: 'pages#takeaway_vouchers'
  get 'motoring_vouchers', to: 'pages#motoring_vouchers'
  get 'fashion_vouchers', to: 'pages#fashion_vouchers'

  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms', to: 'pages#terms'
  
  get 'newsletter/unsubscribe', to: 'newsletters#unsubscribe'
  resources :newsletters
  
  # Error pages (404 etc)
  match "404", to: "errors#not_found"
  

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'web_vouchers#index'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/web_voucher.rb
class WebVoucher < ActiveRecord::Base
  attr_accessible :advert_id, :business_account_id, :details, :expiry_date, :featured, :start_date, :terms, :title, :business_category_id, :status, :town_id, :url, :resource_id, :town, :weblink

  belongs_to :business_account
  has_one :business, :through => :business_account
  belongs_to :business_category
  has_many :web_voucher_analytics

  before_validation :check_weblink

  before_create :set_expiry_date

  acts_as_url :title, :sync_url => true

  validates :title, :details, :terms, :presence => :true

  scope :exclude_featured, lambda {
  	featured = WebVoucher.where("featured = ?", true)
  	return [] unless featured
  	if featured.any?
  	  feat = featured.map(&:id)
  	else
  	  feat = 0
  	end
  	where("id NOT IN (?)", feat)
  }
  
  scope :not_expired, lambda { where("start_date <= ? AND expiry_date >= ?", Date.today.beginning_of_day, Date.today.end_of_day) }
  
  scope :has_paid, where(:status => 'Paid')

  def self.search(search)
  	if search
  		joins(:business).where('title LIKE ? OR details LIKE ? OR web_vouchers.town LIKE ? or business_name LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  	else
  		scoped
  	end
  end

  def to_param
    url
  end


  def set_expiry_date
    self.expiry_date = self.start_date + 1.month
  end
  
  def check_weblink
    if !self.weblink.blank?
	    unless self.weblink[/^http:\/\//] || self.weblink[/^https:\/\//]
  	    self.weblink = 'http://' + self.weblink
  	  end
  	end
  end

  


end

app/controllers/web_vouchers_controller.rb
class WebVouchersController < ApplicationController

before_filter :get_categories
before_filter :authorise_business, only: [:new, :create, :expire_voucher]
before_filter :authenticate_admin_user!, only: [:destroy]


  def index
    @page_title = WV_INDEX_TITLE
    @meta_desc = WV_INDEX_META_DESC
    @meta_key = WV_INDEX_META_KEY
    @web_vouchers = WebVoucher.search(params[:search]).not_expired.has_paid.order("featured DESC, created_at DESC").paginate(:page => params[:page], :per_page => VOUCHERS_PER_PAGE)
  end
  
  def show
  	@voucher = WebVoucher.find_by_url(params[:id])

    @page_title = @voucher.title
    @meta_desc = @voucher.details
    @meta_key = WV_SHOW_META_KEY

    @others = WebVoucher.where("business_account_id = ? AND id != ? AND status = ?", @voucher.business_account_id, @voucher.id, 'Paid').not_expired.limit(3)
    WebVoucherAnalytics.create(web_voucher_id: @voucher.id, viewed: true, remote_ip: request.remote_ip)
  end

  def by_category
    @featured = get_featured_vouchers('business_category_id').not_expired.has_paid
  	@vouchers = WebVoucher.exclude_featured.where("business_category_id = ?", params[:id]).not_expired.has_paid.order("created_at DESC")
    @bus_cat = BusinessCategory.find(params[:id])
    @page_title = "#{@bus_cat.name} Vouchers to print or use online"
  	if @vouchers.empty? && @featured.empty?
  		redirect_to root_url, alert: "Sorry, there are no vouchers in that category"
  	end
  end

  def by_town
    @featured = get_featured_vouchers('town_id').not_expired.has_paid
  	@vouchers = WebVoucher.exclude_featured.where("town_id = ?", params[:id]).not_expired.has_paid.order("created_at DESC")
  	@page_title = "Vouchers in #{@vouchers.first.town.name}" if @vouchers.any?
  	if @vouchers.empty?
  		redirect_to root_url, notice: "Sorry, there are no vouchers in that town"
  	end
  end

  def print
    @voucher = WebVoucher.find_by_url(params[:id])
    WebVoucherAnalytics.create(web_voucher_id: @voucher.id, printed: true, remote_ip: request.remote_ip)
    render :layout => false
  end
  
  
  # Business Accounts Only Below

  def new
    @web_voucher = WebVoucher.new
  end

  def create
    @web_voucher = WebVoucher.new(params[:web_voucher])
    @web_voucher.business_account_id = current_business.id
    @web_voucher.status = 'Pending' # set status to pending until paid
    @web_voucher.town = @web_voucher.business.town

    if @web_voucher.start_date < Date.today
      flash.now[:alert] = "The start date has to be today or later"
    end
      
      # voucher = WebVoucher.where('business_account_id = ?', current_business.id)
      # if voucher.any?
        
        # check if they have any credits
        credits = WebVoucherCredit.where('business_account_id = ?', current_business.id)
        if credits.first.credits > 0
        
          # deduct 1 from credit
          credit_qty = credits.first.credits - 1
          credits.first.update_attributes(credits: credit_qty)
          @web_voucher.status = 'Paid'
          if @web_voucher.save
            redirect_to business_web_vouchers_path, notice: 'Your Voucher has been created.'
          else
            render 'new'
          end
          
        else
          
          # They need to pay for this one
          if @web_voucher.save
            # Paypal
            notify_url = paypal_payments_url
            return_url = business_wv_payment_accepted_url
            cancel_url = business_wv_payment_cancelled_url
            values = {
              :business => PAYPAL_EMAIL_ADDRESS,
              :cmd => '_xclick',
              :upload => 1,
              :notify_url => notify_url,
              :return => return_url,
              :cancel_return => cancel_url,
              :currency_code => 'GBP',
              :invoice => @web_voucher.id,
              :custom => "WV",
              :amount => WEB_VOUCHER_PRICE,
              :item_name => 'Red Hot Voucher Book Web Voucher',
              :quantity => 1
            }
            url = PAYPAL_WEB_URL + values.to_query
            
            redirect_to url
            # GoCardless
            #url_params = {
            #  :redirect_uri => confirm_voucher_payment_url,
            # :amount => WEB_VOUCHER_PRICE,
            #  :name => "Red Hot Voucher - Web Voucher",
            #  :state => @web_voucher.id,
            #  :user => {
            #    :email => current_business.email
            # }
            #}
            # url = GoCardless.new_bill_url(url_params)
        		# redirect_to url
          else
            render 'new'
          end
          
        end
        
      # else
      #         
      #         # This is the first one - its free
      #         @web_voucher.status = 'Paid'
      #         if @web_voucher.save
      #           redirect_to business_web_vouchers_path, notice: 'This Voucher is on us.'
      #         else
      #           render 'new'
      #         end
      #         
      #       end

  end
  
  
  def edit
    @web_voucher = WebVoucher.find_by_id_and_business_account_id(params[:id], current_business.id)
    if @web_voucher.nil?
      redirect_to business_dashboard_path, notice: "That voucher does not exist"
    end
  end
  
  def update
    @web_voucher = WebVoucher.find_by_url(params[:id])
    @web_voucher.update_attributes(params[:web_voucher])
    redirect_to business_web_vouchers_path, notice: "The Web Voucher has been updated"
  end
  
  def expire_voucher
    @web_voucher = WebVoucher.find_by_id_and_business_account_id(params[:id], current_business.id)
    if @web_voucher
      @web_voucher.update_attributes(:expiry_date => (Date.today - 1.day) )
      redirect_to business_web_vouchers_path, notice: "The Web Voucher has been expired"
    else
      flash.now[:error] = "There was an error expiring your voucher"
      redirect_to business_web_vouchers_path
    end
    
  end
  
  
  
  
  # ADMIN ONLY
  def destroy
    @web_voucher = WebVoucher.find(params[:id])
    @web_voucher.destroy
    redirect_to manager_web_vouchers_path, notice: "The web voucher has been deleted"
  end
  

  

end

app/helpers/web_vouchers_helper.rb
module WebVouchersHelper

	def get_web_voucher_views(id)
		views = WebVoucherAnalytics.where('web_voucher_id = ? AND viewed = ?', id, true)
		views.count
	end

	def get_web_voucher_prints(id)
		views = WebVoucherAnalytics.where('web_voucher_id = ? AND printed = ?', id, true)
		views.count
	end
	
	def has_expired?(id)
	 wv = WebVoucher.find(id)
	 if wv.expiry_date < Date.today
	   true
	 else
	   false
	 end
	end

end

app/views/web_vouchers/_form.html.erb
<%= form_for @web_voucher, :html => { class: 'content-form' } do |f| %>
                  <% if @web_voucher.errors.any? %>
                    <div class="error_messages">
                      <h4 class="error">Error processing form</h4>
                      <ul>
                        <% @web_voucher.errors.full_messages.each do |message| %>
                          <li class="error"><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>

									
                  <p>
                    <%= f.label :business_category_id, "Voucher Category" %>
                    <%= f.collection_select :business_category_id, BusinessCategory.order('name ASC'), :id, :name %>
                  </p>

                  <p>
                    <%= f.label :title %>
                    <%= f.text_field :title %>
                  </p>

                  <p>
                    <%= f.label :details %>
                    <%= f.text_area :details %>
                  </p>

                  <p>
                    <%= f.label :terms, 'Terms & Conditions' %>
                    <%= f.text_area :terms %>
                  </p>

									<p>If you would like to redirect users to an external voucher, ie, a voucher hosted on your website, please add the link to the website below.</p>
									
									<p>
                    <%= f.label :weblink, 'External Voucher Website' %>
                    <%= f.text_field :weblink %>
                  </p>

									<p>All Web Vouchers will last one month from the start date. Please make sure you choose the correct start date, as this can not be changed once saved.</p>
                  <p>
                    <%= f.label :start_date, "Start Date" %>
                    <%= f.date_select :start_date, start_year: Time.now.year, end_year: Time.now.year + 1 %>
                  </p>
									<p>You will be taken to PayPal for payment processing, if you have no credits remaining.</p>
                  <p><%= f.submit "Save", class: 'button' %> or <%= link_to "Cancel", business_dashboard_path %></p>
                <% end %>

app/views/web_vouchers/_vouchers.html.erb
<p>&nbsp;</p>
<% for voucher in @web_vouchers %>
    <div class="<%= "featured" if voucher.featured %> introbox">
        <h1><strong><%= link_to voucher.title, web_voucher_path(voucher) %></strong> at <%= voucher.business.business_name %> in <%= voucher.business_account.business.town %></h1>
				<div class="one-third">
					<% if !voucher.business.image.to_s.blank? %>
						<p><%= image_tag voucher.business.image.to_s, width: "150", class: "not-top" %></p>
					<% else %>
						<p style="width: 150px;"></p>
					<% end %>
				</div>

				<div class="one-third textalignleft">
					<i class="<%= voucher.business_category.icon %>"></i> <%= link_to voucher.business_category.name, web_vouchers_by_category_path(id: voucher.business_category.id, business: voucher.business_category.name) %><br />
					<%= voucher.business.business_name %>, <%= voucher.town %>
					<p>Expires: <%= l voucher.expiry_date %></p>
				</div>
				<div class="one-third column-last">
					<%= link_to "Get Voucher", web_voucher_path(voucher), class: "button large red" %>
				</div>
				<div class="clear"></div>
        
        <% if voucher.featured %>
            <%= image_tag 'ribbon-featured.png' %>
        <% end %>
    </div>
<% end %>

<%= will_paginate @web_vouchers %>

app/views/web_vouchers/by_category.html.erb
<!-- begin page title -->
    <section id="page-title">
    	<div class="container clearfix">
						<% cat_name = @vouchers.empty? ? @featured.first.business_category.name : @vouchers.first.business_category.name %>
            <h1><%= cat_name %> Vouchers</h1>
        </div>
    </section>
    <!-- end page title -->
    
    <!-- begin content -->
    <section id="content" class="container clearfix">
    	
        	<div class="two-thirds">

                <% @featured.each do |feat| %>
                    <div class="featured introbox">
                        <h1><strong><%= link_to feat.title, web_voucher_path(feat) %></strong> at <%= feat.business.business_name %> in <%= feat.business_account.business.town %></h1>
                        <div class="one-third">
                            <% if !feat.business.image.to_s.blank? %>
                                <p><%= image_tag feat.business.image.to_s, width: "150", class: "not-top" %></p>
                            <% else %>
                                <p style="width: 150px;"></p>
                            <% end %>
                        </div>

                        <div class="one-third textalignleft">
                            <i class="<%= feat.business_category.icon %>"></i> <%= link_to feat.business_category.name, web_vouchers_by_category_path(id: feat.business_category.id, business: feat.business_category.name) %><br />
                            <%= feat.business.business_name %>, <%= feat.town %>
                            <p>Expires: <%= l feat.expiry_date %></p>
                        </div>
                        <div class="one-third column-last">
                            <%= link_to "Get Voucher", web_voucher_path(feat), class: "button large red" %>
                        </div>
                        <div class="clear"></div>
                        <%= image_tag 'ribbon-featured.png' %>
                    </div>
                <% end %>

                <% @vouchers.each do |voucher| %>
                    <div class="introbox">
                        <h1><strong><%= link_to voucher.title, web_voucher_path(voucher) %></strong> at <%= voucher.business.business_name %> in <%= voucher.business_account.business.town %></h1>
                        <div class="one-third">
                        <% if !voucher.business.image.to_s.blank? %>
                            <p><%= image_tag voucher.business.image.to_s, width: "150", class: "not-top" %></p>
                        <% else %>
                            <p style="width: 150px;"></p>
                        <% end %>
                        </div>

                        <div class="one-third textalignleft">
                            <i class="<%= voucher.business_category.icon %>"></i> <%= link_to voucher.business_category.name, web_vouchers_by_category_path(id: voucher.business_category.id, business: voucher.business_category.name) %><br />
                            <%= voucher.business.business_name %>, <%= voucher.town %>
                            <p>Expires: <%= l voucher.expiry_date %></p>
                        </div>
                        <div class="one-third column-last">
                            <%= link_to "Get Voucher", web_voucher_path(voucher), class: "button large red" %>
                        </div>
                        <div class="clear"></div>
                        <% if voucher.featured %>
                            <%= image_tag 'ribbon-featured.png' %>
                        <% end %>
                    </div>
                <% end %>


            </div>
        
        <div class="cat-menu">    
                <div class="one-third column-last">

                    <%= render 'layouts/side_cat_menu' %>

                    <%= render 'layouts/side_business_login' %>

                    <%= render 'layouts/side_blog' %>
                    
                    <div class="clear"></div>
                </div>
            </div>
        
        
        
    </section>
    <!-- end content -->  

app/views/web_vouchers/by_town.html.erb
<!-- begin page title -->
    <section id="page-title">
    	<div class="container clearfix">
            <h1>Vouchers in <%= @vouchers.first.town.name %></h1>
        </div>
    </section>
    <!-- end page title -->
    
    <!-- begin content -->
    <section id="content" class="container clearfix">
    	
        	<div class="two-thirds">

                <% @featured.each do |feat| %>
                    <div class="introbox">
                        <h1><strong><%= link_to feat.title, web_voucher_path(feat) %></strong> at <%= feat.business.business_name %> in <%= feat.business_account.business.town %></h1>
                        <div class="one-third">
                            <% if !feat.business.image.to_s.blank? %>
                                <p><%= image_tag feat.business.image.to_s, width: "150", class: "not-top" %></p>
                            <% else %>
                                <p style="width: 150px;"></p>
                            <% end %>
                        </div>

                        <div class="one-third textalignleft">
                            <i class="<%= feat.business_category.icon %>"></i> <%= link_to feat.business_category.name, web_vouchers_by_category_path(id: feat.business_category.id, business: feat.business_category.name) %><br />
                            <%= feat.business.business_name %>, <%= feat.town %>
                            <p>Expires: <%= l feat.expiry_date %></p>
                        </div>
                        <div class="one-third column-last">
                            <%= link_to "Get Voucher", web_voucher_path(feat), class: "button large red" %>
                        </div>
                        <div class="clear"></div>
                        <%= image_tag 'ribbon-featured.png' %>
                    </div>
                <% end %>

                <% @vouchers.each do |voucher| %>
                    <div class="introbox">
                        <h1><strong><%= link_to voucher.title, web_voucher_path(voucher) %></strong> at <%= voucher.business.business_name %> in <%= voucher.business_account.business.town %></h1>
                        <div class="one-third">
                           <% if !voucher.business.image.to_s.blank? %>
                                <p><%= image_tag voucher.business.image.to_s, width: "150", class: "not-top" %></p>
                            <% else %>
                                <p style="width: 150px;"></p>
                            <% end %>
                        </div>

                        <div class="one-third textalignleft">
                            <i class="<%= voucher.business_category.icon %>"></i> <%= link_to voucher.business_category.name, web_vouchers_by_category_path(id: voucher.business_category.id, business: voucher.business_category.name) %><br />
                            <%= voucher.business.business_name %>, <%= voucher.town %>
                            <p>Expires: <%= l voucher.expiry_date %></p>
                        </div>
                        <div class="one-third column-last">
                            <%= link_to "Get Voucher", web_voucher_path(voucher), class: "button large red" %>
                        </div>
                        <div class="clear"></div>
                        <% if voucher.featured %>
                            <%= image_tag 'ribbon-featured.png' %>
                        <% end %>
                    </div>
                <% end %>


            </div>
        
        <div class="cat-menu">    
                <div class="one-third column-last">

                    <%= render 'layouts/side_cat_menu' %>

                    <%= render 'layouts/side_business_login' %>

                    <%= render 'layouts/side_blog' %>
                    
                    <div class="clear"></div>
                </div>
            </div>
        
        
        
    </section>
    <!-- end content -->  

app/views/web_vouchers/edit.html.erb
<!-- begin page title -->
    <section id="page-title">
    	<div class="container clearfix">
            <h1>Create A Web Voucher</h1>
        </div>
    </section>
    <!-- end page title -->


<%= render 'businesses/menu' %>
  
<!-- begin main content -->
  <section id="main" class="three-fourths column-last">
      <h2>Edit Your Web Voucher</h2>

			<%= form_for @web_voucher, :html => { class: 'content-form' } do |f| %>
			    <% if @web_voucher.errors.any? %>
			       <div class="error_messages">
			          <h4 class="error">Error processing form</h4>
			             <ul>
			                <% @web_voucher.errors.full_messages.each do |message| %>
			                   <li class="error"><%= message %></li>
			                <% end %>
			       </div>
			    <% end %>

			    <p>
	          <%= f.label :business_category_id, "Voucher Category" %>
	          <%= f.collection_select :business_category_id, BusinessCategory.order('name ASC'), :id, :name %>
	        </p>

	        <p>
	          <%= f.label :town, "Town" %>
	          <%= f.text_field :town %>
	        </p>

	        <p>
	          <%= f.label :title %>
	          <%= f.text_field :title %>
	        </p>

	        <p>
	          <%= f.label :details %>
	          <%= f.text_area :details %>
	        </p>

	        <p>
	          <%= f.label :terms, 'Terms & Conditions' %>
	          <%= f.text_area :terms %>
	        </p>
	
					<p>
	          <%= f.label :weblink, "External Voucher Website" %>
	          <%= f.text_field :weblink %>
	        </p>

	        <p><%= f.submit "Save", class: 'button' %> or <%= link_to "Cancel", business_dashboard_path %></p>
	      <% end %>

  </section>
  <!-- end main content -->
</section>
<!-- end content -->

app/views/web_vouchers/index.html.erb
<!-- begin page title -->
    <section id="page-title">
    	<div class="container clearfix">
				<ul class="voucher-cats">
					<% @categories.each do |cat| %>
			        <li><%= link_to web_vouchers_by_category_path(id: cat, business: cat.name) do %>
										<i class="<%= cat.icon %>" title="<%= cat.name %> Vouchers"></i>
									<% end %>
							</li>
			    <% end %>
				</ul>
        </div>
    </section>
    <!-- end page title -->
    
    <!-- begin content -->
    <section id="content" class="container clearfix">
    	
        <section>
	
        	<div class="two-thirds">
                <%= form_tag web_vouchers_path, class: "content-form", :method => 'get', :id => "web_vouchers_search" do %>
                    <%= text_field_tag :search, params[:search], class: 'search-input', :placeholder => "Search Vouchers", :autocomplete => "off" %>

                    <div id="vouchers"><%= render 'vouchers' %></div>
                    <% end %>
                
            </div>

            <div class="cat-menu">    
                <div class="one-third column-last">

                    <%= render 'layouts/side_cat_menu' %>

                    <%= render 'layouts/side_business_login' %>

                    <%= render 'layouts/side_blog' %>
                    
                    <div class="clear"></div>
                </div>
            </div>

        </section>
        
    </section>
    <!-- end content -->  

app/views/web_vouchers/index.js.erb
$('#vouchers').html('<%= escape_javascript(render("vouchers")) %>');