config/routes.rb
Myapp::Application.routes.draw do
  
  


  
  get "contact_messages/new"

  get 'business_signup', to: 'business_accounts#new', as: 'business_signup'
  get 'business_login', to: 'business_sessions#new', as: 'business_login'
  get 'business_logout', to: 'business_sessions#destroy', as: 'business_logout'
  
  get 'business_accounts/change_password', to: 'business_accounts#change_password'
  post 'business_accounts/send_change_password', to: 'business_accounts#send_change_password'
  resources :business_accounts
  
  get 'business_sessions/reset_password', to: 'business_sessions#reset_password'
  post 'business_sessions/send_new_password', to: 'business_sessions#send_new_password'
  resources :business_sessions

  get 'business/dashboard', to: 'businesses#dashboard', as: 'business/dashboard'
  get 'business/adverts', to: 'businesses#adverts', as: 'business/adverts'
  match 'business/web_vouchers', to: 'businesses#web_vouchers', via: [:get, :post]
  get 'business/wv_payment_cancelled', to: 'businesses#wv_payment_cancelled'
  get 'business/wv_payment_accepted', to: 'businesses#wv_payment_accepted'
  get 'business/ad_payment_cancelled', to: 'businesses#ad_payment_cancelled'
  get 'business/ad_payment_accepted', to: 'businesses#ad_payment_accepted'
  get 'business/new_book_advert', to: 'businesses#new_book_advert'
  post 'business/create_book_advert', to: 'businesses#create_book_advert'
  get 'business/directory', to: 'businesses#directory'
  post 'business/process_review', to: 'businesses#process_review'
  get 'business/search', to: 'businesses#search'
  get 'business/my_events', to: 'businesses#my_events'
  resources :businesses

  # Manager Area
  get 'manager', to: 'manager#index', as: 'manager/index'
  get "manager/dashboard", to: 'manager#dashboard', as: 'manager/dashboard'
  get 'manager/booklets', to: 'manager#booklets', as: 'manager/booklets'
  get 'manager/businesses', to: 'manager#businesses', as: 'manager/businesses'
  get 'manager/web_vouchers', to: 'manager#web_vouchers', as: 'manager/web_vouchers'
  get 'manager/settings', to: 'manager#settings', as: 'manager/settings'
  get 'manager/towns', to: 'manager#towns', as: 'manager/towns'
  get 'manager/business_categories', to: 'manager#business_categories', as: 'manager/business_categories'
  get 'manager/advert_sizes', to: 'manager#advert_sizes', as: 'manager/advert_sizes'
  get 'manager/add_credits', to: 'manager#add_credits', as: 'manager/add_credits'
  post 'manager/update_credits', to: 'manager#update_credits', as: 'manager/update_credits'
  get 'manager/new_business_account', to: 'manager#new_business_account', as: 'manager/new_business_account'
  post 'manager/create_business_account', to: 'manager#create_business_account', as: 'manager/create_business_account'
  get 'manager/new_business_profile', to: 'manager#new_business_profile', as: 'manager/new_business_profile'
  post 'manager/create_business_profile', to: 'manager#create_business_profile', as: 'manager/create_business_profile'
  get 'manager/edit_business_profile', to: 'manager#edit_business_profile', as: 'manager/edit_business_profile'
  post 'manager/update_business_profile', to: 'manager#update_business_profile', as: 'manager/update_business_profile'
  get 'manager/edit_web_voucher', to: 'manager#edit_web_voucher', as: 'manager/edit_web_voucher'
  put 'manager/update_web_voucher', to: 'manager#update_web_voucher', as: 'manager/update_web_voucher'
  get 'manager/expire_web_voucher', to: 'manager#expire_web_voucher', as: 'manager/expire_web_voucher'
  get 'manager/marketing_email', to: 'manager#marketing_email', as: 'manager/marketing_email'
  post 'manager/send_marketing_email', to: 'manager#send_marketing_email', as: 'manager/send_marketing_email'
  get 'manager/new_web_voucher', to: 'manager#new_web_voucher'
  post 'manager/create_web_voucher', to: 'manager#create_web_voucher'
  get 'manager/set_advert_paid', to: 'manager#set_advert_paid'
  get 'manager/articles', to: 'manager#articles'
  get 'manager/business_reviews', to: 'manager#business_reviews'
  get 'manager/edit_review', to: 'manager#edit_review'
  put 'manager/update_review', to: 'manager#update_review', as: 'manager/update_review'
  get 'manager/sign_in_as_business', to: 'manager#sign_in_as_business'
  
  get 'contacts/create_a_business_listing', to: 'contacts#create_a_business_listing'
  get 'contacts/totally_delete_contact', to: 'contacts#totally_delete_contact'
  post 'contacts/add_contact_note', to: 'contacts#add_contact_note'
  resources :contacts
  resources :commissions
  resources :events
  resources :appointments
  resources :testimonials
  
  # Manager Reports
  get 'manager/reports', to: 'manager#reports'
  get 'manager/commission_report', to: 'manager#commission_report'
  get 'manager/commission_by_booklet', to: 'manager#commission_by_booklet'
  get 'manager/commission_by_booklet_print', to: 'manager#commission_by_booklet_print'
  
  get 'manager/create_contacts_from_existing_businesses', to: 'manager#create_contacts_from_existing_businesses'
  
  resources :towns
  resources :business_categories
  resources :advert_sizes
  
  resources :booklets
  
  resources :paypal_payments

  get 'print_voucher', to: 'web_vouchers#print', as: 'print_voucher'
  get 'web_vouchers/by_category'
  get 'web_vouchers/by_town'
  get 'web_vouchers/expire_voucher'
  resources :web_vouchers
  
  

  get 'advert/invoice', to: 'adverts#invoice'
  get 'print_invoice', to: 'adverts#print', as: 'print_invoice'
  get 'advert/pay_advert', to: 'adverts#pay_advert'
  resources :adverts
  
  get 'advert_comments/accept_design', to: 'advert_comments#accept_design'
  resources :advert_comments
  
  match 'articles/category', to: 'articles#category'
  resources :articles
  resources :article_comments

  # Static Pages
  get 'advertising', to: 'pages#advertising'
  get 'contact_us', to: 'pages#contact'
  post 'send_contact_form', to: 'pages#send_contact_form'
  get 'advert_enquiry', to: 'pages#advert_enquiry'
  post 'send_advert_enquiry', to: 'pages#send_advert_enquiry'

  get 'restaurant_vouchers', to: 'pages#restaurant_vouchers'
  get 'health_and_beauty_vouchers', to: 'pages#health_and_beauty_vouchers'
  get 'bars_pubs_and_clubs_vouchers', to: 'pages#bars_vouchers'
  get 'fast_food_and_takeaway_vouchers', to: 'pages#takeaway_vouchers'
  get 'motoring_vouchers', to: 'pages#motoring_vouchers'
  get 'fashion_vouchers', to: 'pages#fashion_vouchers'

  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms', to: 'pages#terms'
  
  get 'newsletter/unsubscribe', to: 'newsletters#unsubscribe'
  resources :newsletters
  
  # Error pages (404 etc)
  match "404", to: "errors#not_found"
  

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'web_vouchers#index'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/advert.rb
class Advert < ActiveRecord::Base
  attr_accessible :advert_cost, :advert_size_id, :booklet_id, :business_id, :paid, :image, :valid_from, :valid_to, :featured, :resource_id, :admin_user_id

  belongs_to :booklet
  belongs_to :business
  belongs_to :advert_size
  belongs_to :admin_user
  has_many :advert_comments

  mount_uploader :image, ImageUploader
  
  before_create :set_valid_from, :set_expiry_date, :set_cost_if_not_defined
  
  def total_units
    advert_size.page_unit
  end

  def set_valid_from
    self.valid_from = self.booklet.start_date
  end
  
  def set_expiry_date
    self.valid_to = self.valid_from.at_end_of_month
  end
  
  def set_cost_if_not_defined
    if self.advert_cost.nil?
      ad_cost = AdvertSize.find(self.advert_size_id)
      self.advert_cost = ad_cost.cost
    else
      self.advert_cost
    end
  end

end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  
  before_filter :authorise_business, only: [:pay_advert, :invoice, :print]
  before_filter :authenticate_admin_user!, only: [:new, :create]
  
  def show
    @page_title = "View your booklet voucher"
    @advert_comment = AdvertComment.new
    # if admin logged in get by id
    if admin_user_signed_in?
      @advert = Advert.find(params[:id])
    else
      @advert = Advert.where("id = ? AND business_id = ?", params[:id], current_business.business.id).first
    end
    
    if @advert
      @comments = AdvertComment.where("advert_id = ?", @advert.id).order('created_at DESC')
    else
      redirect_to business_dashboard_path, notice: "Sorry, that Voucher does not exist"
    end
  end
    
  def pay_advert
    advert = Advert.find(params[:id])
    # Paypal
            notify_url = paypal_payments_url
            return_url = business_ad_payment_accepted_url
            cancel_url = business_ad_payment_cancelled_url
            values = {
              :business => PAYPAL_EMAIL_ADDRESS,
              :cmd => '_xclick',
              :upload => 1,
              :notify_url => notify_url,
              :return => return_url,
              :cancel_return => cancel_url,
              :currency_code => 'GBP',
              :invoice => advert.id,
              :custom => "AD",
              :amount => advert.advert_cost,
              :item_name => 'Red Hot Voucher Book Advertisement',
              :quantity => 1
            }
            url = PAYPAL_WEB_URL + values.to_query
            
            redirect_to url
  end
  
  def invoice
    @advert = Advert.find(params[:id])
  end
  
  def print
    @advert = Advert.find(params[:id])
    render :layout => false
  end
  
  # Admin Only
  
  def new
    @advert = Advert.new
  end
  
  def create
    @advert = Advert.new(params[:advert])
    @advert.paid = false
    if @advert.save
      redirect_to booklet_path(@advert.booklet_id), notice: "The advert has been created"
    else
      render 'new'
    end
  end
  
  def destroy
    @advert = Advert.find(params[:id])
    @advert.destroy
    redirect_to booklet_path(@advert.booklet_id), notice: "The advert has been deleted"
  end
  
end

app/helpers/adverts_helper.rb
module AdvertsHelper
  
  def has_been_accepted(ad)
    ac = AdvertComment.where("advert_id = ? AND accepted = ?", ad, true)
    if ac.any?
      true
    else
      false
    end
  end
  
end

app/views/adverts/invoice.html.erb
<!-- begin page title -->
    <section id="page-title">
    	<div class="container clearfix">
            <h1>Your Red Hot Voucher Invoice</h1>
        </div>
    </section>
    <!-- end page title -->
    
    <!-- begin content -->
    <section id="content" class="container clearfix">
    	<p><%= link_to print_invoice_path(id: @advert), target: "_blank", class: "button large" do %> <i class="icon-print white icon-large"></i> Print <% end %></p>
		<h1>Invoice</h1>
			<div class="one-third">
				<h3><%= @advert.business.business_name %></h3>
				<p><%= @advert.business.street %><br />
					<%= @advert.business.town %><br />
					<%= @advert.business.county %><br />
					<%= @advert.business.postcode %>
				</p>
			</div>
			<div class="one-third">
				
			</div>
			<div class="one-third column-last">
				
			</div>
			<div class="clear"></div>
			<div>
				<table class="gen-table">
					<thead>
						<tr>
							<th>Description</th>
							<th>Price</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= @advert.advert_size.name %> Advertisement in the <%= @advert.booklet.name %> Edition of the Red Hot Vocher Book.</td>
							<td><%= number_to_currency(@advert.advert_cost) %></td>
						</tr>
						<tr>
							<td style="text-align: right;"><strong>Total:</strong></td>
							<td><%= number_to_currency(@advert.advert_cost) %></td>
						</tr>
					</tbody>
				</table>
			</div>

			<p>Payment required before <strong><%= l @advert.booklet.cut_off_date %></strong>. Please make cheques payable to DN Media.</p>
			<p>Bank transfers accepted, DN Media, Natwest PLC, Account No: 21770824, Sort Code 60-24-77.</p>
		</section>
	
</section>

app/views/adverts/new.html.erb
<!-- begin page title -->
    <section id="page-title">
    	<div class="container clearfix">
            <h1>Create A New Advert</h1>
        </div>
    </section>
    <!-- end page title -->
    
    <!-- begin content -->
    <section id="content" class="container clearfix">
				<%= form_for @advert, :html => { class: 'content-form' } do |f| %>
				
				<% if @advert.errors.any? %>
          <div class="error_messages">
            <h4 class="error">Error processing form</h4>
            <ul>
              <% @advert.errors.full_messages.each do |message| %>
                <li class="error"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

				<%= f.hidden_field :booklet_id, value: params[:booklet] %>
				<p>
          <%= f.label :business_id, "Business" %>
          <%= f.collection_select :business_id, Business.order('business_name ASC'), :id, :business_name, prompt: true %>
        </p>

				<p>
          <%= f.label :advert_size_id, "Advert Size" %>
          <%= f.collection_select :advert_size_id, AdvertSize.order('name ASC'), :id, :name, prompt: true %>
        </p>

				<p>
          <%= f.label :advert_cost, "Advert Cost (if different than standard cost - else leave blank)" %>
          <%= f.text_field :advert_cost %>
        </p>

        <p>
          <%= f.label :admin_user_id, "Sold By" %>
          <%= f.collection_select :admin_user_id, AdminUser.order('fullname ASC'), :id, :fullname, prompt: true %>
        </p>

				<p><%= f.submit "Save", class: 'button' %> or <%= link_to "Cancel", manager_dashboard_path %></p>
				
				<% end %>
		</section>
		
</section>

app/views/adverts/print.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset='UTF-8'>
	
	<title>Invoice</title>

<style type="text/css">

	* { margin: 0; padding: 0; }
body { font: 14px/1.4 Georgia, serif; }
#page-wrap { width: 600px; margin: 0 auto; }

textarea { border: 0; font: 14px Georgia, Serif; overflow: hidden; resize: none; }
table { border-collapse: collapse; }
table td, table th { border: 1px solid black; padding: 5px; }

#header { height: 15px; width: 100%; margin: 20px 0; background: #222; text-align: center; color: white; font: bold 15px Helvetica, Sans-Serif; text-decoration: uppercase; letter-spacing: 20px; padding: 8px 0px; }

#address { width: 250px; height: 150px; float: left; }
#customer { overflow: hidden; }
.identity { float: left;}
.logo { float: left; position: relative; margin-bottom: 25px; border: 1px solid #fff; max-width: 540px; max-height: 100px; overflow: hidden; }



#customer-title { font-size: 16px; font-weight: bold; float: left; }

#meta { margin-top: 1px; width: 300px; float: right; }
#meta td { text-align: right;  }
#meta td.meta-head { text-align: left; background: #eee; }
#meta td textarea { width: 100%; height: 20px; text-align: right; }

#items { clear: both; width: 100%; margin: 30px 0 0 0; border: 1px solid black; }
#items th { background: #eee; }
#items textarea { width: 80px; height: 50px; }
#items tr.item-row td { border: 0; vertical-align: top; }
#items td.description { width: 300px; }
#items td.item-name { width: 175px; }
#items td.description textarea, #items td.item-name textarea { width: 100%; }
#items td.total-line { border-right: 0; text-align: right; }
#items td.total-value { border-left: 0; padding: 10px; }
#items td.total-value textarea { height: 20px; background: none; }
#items td.balance { background: #eee; }
#items td.blank { border: 0; }

#terms { text-align: center; margin: 20px 0 0 0; }
#terms h5 { text-transform: uppercase; font: 13px Helvetica, Sans-Serif; letter-spacing: 10px; border-bottom: 1px solid black; padding: 0 0 8px 0; margin: 0 0 8px 0; }
#terms textarea { width: 100%; text-align: center;}

textarea:hover, textarea:focus, #items td.total-value textarea:hover, #items td.total-value textarea:focus, .delete:hover { background-color:#EEFF88; }

.delete-wpr { position: relative; }
.delete { display: block; color: #000; text-decoration: none; position: absolute; background: #EEEEEE; font-weight: bold; padding: 0px 3px; border: 1px solid; top: -6px; left: -22px; font-family: Verdana; font-size: 12px; }
</style>
</head>

<body onload="window.print();">

	<div id="page-wrap">

		<div id="header">INVOICE</div>
		
		<div class="logo">
                <%= image_tag "web-logo.png" %>
            </div>

		<div class="identity">
		
            <p><strong>DN Media</strong><br />
			6 Carlton Grove<br />
			Horwich<br />
			Phone: 0161 408 3334</p>
		
		</div>
		
		<div style="clear:both"></div>
		
		<div id="customer">

            <div id="customer-title"><%= @advert.business.business_name %>
            	<p><%= @advert.business.street %><br />
					<%= @advert.business.town %><br />
					<%= @advert.business.county %><br />
					<%= @advert.business.postcode %>
				</p></div>

            <table id="meta">
                <tr>
                    <td class="meta-head">Invoice #</td>
                    <td>000<%= @advert.id %></td>
                </tr>
                <tr>

                    <td class="meta-head">Date</td>
                    <td><%= l @advert.created_at %></td>
                </tr>
                <tr>
                    <td class="meta-head">Amount Due</td>
                    <td><div class="due"><%= number_to_currency(@advert.advert_cost) %></div></td>
                </tr>

            </table>
		
		</div>
		
		<table id="items">
		
		  <tr>
		      <th width="80%">Description</th>
		      <th>Price</th>
		  </tr>
		  
		  <tr class="item-row">
		      <td class="description"><%= @advert.advert_size.name %> Advertisement in the <%= @advert.booklet.name %> Edition of the Red Hot Voucher Book.</td>
		      <td><span class="price"><%= number_to_currency(@advert.advert_cost) %></span></td>
		  </tr>
		  
		  
		  
		  <tr>
		      <td class="total-line"><strong>Subtotal</strong></td>
		      <td class="total-value"><div id="subtotal"><%= number_to_currency(@advert.advert_cost) %></div></td>
		  </tr>
		  <tr>
		      <td class="total-line"><strong>Total</strong></td>
		      <td class="total-value"><div id="total"><strong><%= number_to_currency(@advert.advert_cost) %></strong></div></td>
		  </tr>
		
		</table>
		
		<div id="terms">
		  <h5>Terms</h5>
		  <p>Payment required before <strong><%= l @advert.booklet.cut_off_date %></strong>. Please make cheques payable to DN Media.</p>
			<p>Bank transfers accepted, DN Media, Natwest PLC, Account No: 21770824, Sort Code 60-24-77.</p>
		</div>
	
	</div>
	
</body>

</html>

app/views/adverts/show.html.erb
<!-- begin page title -->
    <section id="page-title">
    	<div class="container clearfix">
            <h1>Your Red Hot Voucher</h1>
        </div>
    </section>
    <!-- end page title -->
    
    <!-- begin content -->
    <section id="content" class="container clearfix">

			<div class="two-thirds">
				<h3>Your Voucher For The <%= @advert.booklet.town.name %> Book <%= @advert.booklet.month %> <%= @advert.booklet.year %></h3>
				<section id='comments'>
					<ol class='comment-list'>
						<% if @comments.any? %>
							<% @comments.each do |comment| %>
								<li class='comment'>
									<% accepted =  comment.accepted == true ? 'comment-accepted' : '' %>
									<div class="comment-wrap <%= accepted %>">
										<div class="comment-details">
											<div class="comment-author">
												<% name = comment.admin_user_id.nil? ? comment.business_account.business.business_name : "#{comment.admin_user.fullname} (Red Hot Voucher Book)" %>
												<%= link_to name, '#' %>
											</div>
											<div class="comment-meta">
												<%= l comment.created_at %>
											</div>
											<div class="comment-content">
												<p><%= comment.comment %></p>
												<%= link_to File.basename(comment.image.to_s), comment.image.to_s, target: '_blank' if comment.image %>
												<% if !comment.image.blank? && !comment.admin_user_id.blank? %>
													<% if comment.accepted == true %>
														<p>Design Accepted</p>
													<% else %>
														<%= link_to "Accept Design", advert_comments_accept_design_path(id: comment.id), class: 'button' %>
													<% end %>
												<% end %>
											</div>
										</div>
									</div>
								</li>
							<% end %>
						<% else %>
							<p>Your design will show up here soon. You will receive an email once it has been created.</p>
						<% end %>
					</ol>
				</section>
				<section id="respond">
					<h3>Add A Comment</h3>
					<p>Please add any changes to your design that you require, plus you can also upload any logos or images that you would like to be included in your design.</p>
					
					<%= form_for @advert_comment, :html => {id: "comment-form"} do |f| %>
					
						<p>
					    <%= f.label :comment %>
					    <%= f.text_area :comment %>
					  </p>
					
						<p>
							<%= f.label :image, 'File Upload' %>
					    <%= f.file_field :image %>
						</p>
						<%= f.hidden_field :advert_id, value: params[:id] %>
						<p class='form-submit'><%= f.submit "Add Comment", class: 'button' %></p>
					
					<% end %>
					
				</section>
				
			</div>
			
			<div class="one-third column-last">
				<h4>Booklet Voucher Details</h4>
				<p><strong>Town:</strong> <%= @advert.booklet.town.name %><br />
				<strong>Date:</strong> <%= @advert.booklet.month %> <%= @advert.booklet.year %><br />
				<strong>Size:</strong> <%= @advert.advert_size.name %><br />
				<strong>Cost:</strong> <%= number_to_currency(@advert.advert_cost) %></p>
				<% status = @advert.paid == true ? 'Paid' : 'Unpaid' %>
				<p><strong>Status:</strong> <%= status %></p>
				<% accepted = has_been_accepted(@advert.id) == true ? '<i class="icon-ok green"></i>' : '<i class="icon-remove red"></i>' %>
				<p><strong>Accepted:</strong> <%= accepted.html_safe %></p>
				<% if current_business %>
					<p><%= link_to "Pay #{number_to_currency(@advert.advert_cost)}", advert_pay_advert_path(id:@advert.id), class: 'button green' if @advert.paid == false %></p>
				<% end %>
				<p><%= link_to "Invoice", advert_invoice_path(id: @advert.id) if @advert.paid == true %></p>
			</div>

		</section>
			
	</section>